### ISSUE TITLE
Implement an abstraction over pthread and windows thread synchronisation primitives

### ISSUE THREAD

**Issue by iphydf** [TokTok/c-toxcore#1002]
It should use pthread for posix systems, windows threads for windows systems. We should get rid of the dependency on pthread-win32 and instead provide small wrappers around OS-specific code ourselves. This makes compiling with msvc easier.

**Comment by nurupo** [comment]
>Implement an abstraction over pthread and windows thread synchronisation primitives

So, "Implement pthreads-win32".

Someone already has done that already though, here https://www.sourceware.org/pthreads-win32/.

**Comment by zoff99** [comment]
last release was in 2099 :-)

```
RELEASE 2.10.0
--------------
(2099-99-99)
```

**Comment by iphydf** [comment]
1. Having to `#include <pthread.h>` means all the "portable" C code is now tainted with OS-specific includes, making static analysis a lot harder.
2. We don't actually need most of pthreads-win32, we only need mutexes, so making a small wrapper that exposes exactly what we need allows us to strictly limit the amount of system-dependent APIs we use. So no, this is not "implement pthreads-win32".

**Comment by nurupo** [comment]
1. If all you want is not to bring OS-specific includes in the scope, then just hide them, make a `tox_pthread.h` and `tox_pthread.c` wrapper around `pthread.h` that will hide them inside `tox_pthread.c`.
2. Making such wrapper is easy and will also allow us to use all of the other features of `pthreads-win32` besides mutexes if a need arises, because otherwise, if we would need more stuff than mutexes, we'd need to either implement the missing OS abstraction ourselves or scrap all the mutex code you are proposing to write and implement this `pthread.h` wrapper I'm suggesting.

`pthread.h` wrapper hiding the OS-specific includes is easy to make, requires no maintenance, `pthreads-win32` on Windows is already implemented and battle-tested so there are unlikely to be bugs, and it's easily extendable.
