### ISSUE TITLE
Android compile failed on Jenkins

### ISSUE THREAD

**Issue by Jefferson-111** [TokTok/c-toxcore#1065]
I want to use the latest file(.so) for android ,but In Jenkins was failed:  https://build.tox.chat/job/libtoxcore-toktok_build_android_arm64_static_release/   How can I upgrade the latest file(.so)

**Comment by iphydf** [comment]
Jenkins should start using the scripts/* makefiles.

**Comment by nurupo** [comment]
Jenkins should shutdown to be honest, no one uses it anymore and I don't want to maintain it. The only builds on there that are being somewhat used are nightly qTox builds, which could be replaced with the GitHub Releases script I'm writing, and maybe also musl toxic builds, which can be done on toxic's Travis-CI too.

@iphydf where can I find `scripts/*` to build c-toxcore, perhaps it's something obvious and I could eyeball what it does differently. I somewhat doubt that your suggestion of using the script on Jenkins would work though, at least without modifying the script, as for it to work the script would need to be customizable, e.g. I should be able to tell it where the Android toolchain is installed, where the already pre-build sodium, vpx, etc. are located and so on.

**Comment by nurupo** [comment]
@wangxuefang have you tried building toxcore for Android yourself? Might be a faster route and you wouldn't be affected if Jenkins does indeed shut down.

**Comment by zoff99** [comment]
@nurupo is the "--enable-minimal" libsodium configure settings active? that should be removed

**Comment by nurupo** [comment]
@zoff99 yes, it is

```bash
./configure --prefix="$PREFIX_DIR" --disable-shared --enable-static --host="$TOOLCHAIN" --disable-soname-versions --disable-pie --enable-minimal --with-sysroot=$TOOLCHAIN_DIR/sysroot
```

I will try removing that and see if it works. It worked before with `--enable-minimal` though.

**Comment by nurupo** [comment]
@zoff99 that fixed the build!

**Comment by nurupo** [comment]
@wangxuefang should be fixed now.

**Comment by wangxuefang** [comment]
@nurupo  I'm trying to build toxcore by myself, but i'm a novice in this, I'm trying to build in Android Stuido and NDK, but failed, can you give me a document about how to build toxcore? Thank you.

**Comment by wangxuefang** [comment]
@nurupo  Did the jenkins has shutdown? I can't access the jenkins now.

**Comment by nurupo** [comment]
You first need to build all of toxcore's dependencies: sodium, vpx and opus and then build toxcore linking it to those. You cross-compile those as usually, using the NDK toolchain, but vpx requires some non-standard arguments so check its README. It's a bit too much to explain it all in here...

@iphydf is saying he got some makefiles somewhere, I think he talks about [the Java toxcore bindings](https://github.com/TokTok/jvm-toxcore-c/tree/master/scripts), it supposedly automates everything for you or close to it, so it should be easier to use, you could give that a try. (There is also [an example echo bot written in Java](https://github.com/TokTok/echobot-jvm/blob/master/src/main/java/im/tox/echobot/EchoBot.java) that uses the bindings).

Jenkins is up for me.

**Comment by wangxuefang** [comment]
@nurupo  @iphydf  It seems complicated, can you compile a new file of .so  for my android app?Jenkins:https://build.tox.chat/job/tox4j_build_android_arm64_release/  this is for arm64,but it seems failed. as  arm64,I also need the files of .so on  armeabi-v7a,x86.  thank you.

**Comment by nurupo** [comment]
@wangxuefang you originally linked to https://build.tox.chat/job/libtoxcore-toktok_build_android_arm64_static_release/ which did get fixed, it should contain the .so files and whatnot. iphy's jars should also contain those. As far as that tox4j jenkins job you are linking to now, I'd need @iphydf's assistance on that one, but he probably thinks it's a pointless waste of time since the makefiles in the repo work and there are bintray artifacts which can be used directly in maven/whatnot, what more would one need? I can't really blame him for thinking that way, it is a bit pointless waste of time indeed, well, aside from the fact that Antox uses it and thus it has been stuck on toxcore v0.1.x for a year now with the tox4j builds failing all this time, but then Antox could be modified to pull the jars off maven repo on bintray instead of fixing the tox4j jenkins build so it's not really an argument.

**Comment by iphydf** [comment]
Jenkins is dead.

**Comment by nurupo** [comment]
RIP
