### ISSUE TITLE
Tox conference connected callback isn't triggered

### ISSUE THREAD

**Issue by endoffile78** [TokTok/c-toxcore#1269]
I'm adding persistent groupchats to uTox and when I try to send a message to the group after it is loaded toxcore says that it fails to send (error 4). I added in a the conference connected callback and it never gets triggered, I tried creating a new groupchat it also never triggers the connected callback.

**Comment by zugz** [comment]
* Tuesday, 2018-11-20 at 13:31 -0800 - endoffile78 <notifications@github.com>:

>I'm adding persistent groupchats to uTox and when I try to send 
>a message to the group after it is loaded toxcore says that it fails to 
>send (error 4).

That's the error message you get if you try to send a message to a group 
when you're the only one in the group. It doesn't even try to send the 
message, because there's no-one to send it to. It is a bit strange not 
to distinguish in the error code between this case and an actual failed 
attempt to send a message. Maybe we should we make it -5, and then the 
client can print a nice error message explaining that there's no-one in 
the group?

>I added in a the conference connected callback and it never gets 
>triggered, I tried creating a new groupchat it also never triggers the 
>connected callback.

That's correct behaviour. That callback is triggered only after an 
accepted invitation.

**Comment by endoffile78** [comment]
Yes I think we should distinguish between them. 

Why is group connect only for groupchats you were invited to, couldn't it be useful for persistent groups too to make sure that you are actually connected to the group.

**Comment by zugz** [comment]
* Tuesday, 2018-11-20 at 14:20 -0800 - endoffile78 <notifications@github.com>:

>Yes I think we should distinguish between them.

OK, I'll make a PR for it soon.

>Why is group connect only for groupchats you were invited to

It's because there's some setting up that's required before you can 
successfully invite someone else to the group. If I remember correctly, 
you don't even consider yourself to be part of the group until that 
event gets triggered.

>, couldn't it be useful for persistent groups too to make sure that you 
>are actually connected to the group.

But it's different - you can invite someone to the group even if you 
don't currently see any other members, and everything will get connected 
together properly if they turn up later.

Once you've successfully joined, even if there's been a save and load 
cycle in between, all that "actually connected to the group" could mean 
is that there's someone else in the group online. You can directly check 
for that by testing (tox_conference_peer_count(...) >= 2).

**Comment by zugz** [comment]
>It's because there's some setting up that's required before you can
>successfully invite someone else to the group.

To be more precise: the point is that before you can sensibly do 
anything with the group, including inviting others, you need to know the 
"peer number" by which the group knows you. You find this out only 
a little after accepting an invite, and the event is there to tell you 
when that is. Your peer number then remains constant throughout the 
subsequent lifetime of the group.

**Comment by zugz** [comment]
* Tuesday, 2018-11-20 at 14:08 -0800 - zugz <notifications@github.com>:

>Maybe we should we make it -5

Actually -3 makes more sense (same as before the connected event). Done 
in #1271.
