### ISSUE TITLE
Feature Requrest: Real Time Text?

### ISSUE THREAD

**Issue by symgryph** [TokTok/c-toxcore#1292]
Real Time text is a nifty feature of the old 'talk' command. You could see what they other person was typing. Any plans for this? Its a really cool feature!

**Comment by iphydf** [comment]
That's an interesting idea. It would already be possible with toxcore today, if a client implemented it.

**Comment by zoff99** [comment]
@symgryph would you be interested to help code it? do you have C programming knowledge?
any help welcome

**Comment by zugz** [comment]
I for one would love to see this in tox! It's been a dream of mine for 
some time.

**Comment by iphydf** [comment]
In toxcore, there are no changes needed for this feature. Custom packets can do exactly that.

**Comment by zoff99** [comment]
@zugz dude get some bigger and hotter dreams :-)

**Comment by mrwicks** [comment]
**I** can do it!

Under linux, on a text client.  The problem is that this will be entirely non standard.  Most clients expect that when they get a block of text, that's the whole message and they will display it that way.

There's also additional overhead (every character = 1 packet!), PLUS it's easier to break the encryption when doing this.

Ping me on TOX is you like:

2779E73EE1BE4E85A52DDA1E0E0DE8006905250171725CD64BE0ED1C29DACC4C03491A64CDA5

I've been planning on adding this feature myself, because ytalk is way better than any IM out there.  Talking in voice is an intimate way to talk, talking with text messages more distant, and ytalk is the best of both.

Ideally this should be an option with TOK that can be turned off on either end.  I wouldn't want this to be done to somebody with a limited data rate plan on 3g.

**Comment by zoff99** [comment]
TOK ??

**Comment by mrwicks** [comment]
> TOK ??

Oops, corrected it.  TOK as far as I know is Java.  It also consumes a LOT of battery power.  I'm interested in working on the core protocol and am not so interested in the clients (yet).

I had considerable difficulty with qTox and tuntox establishing P2P UDP connections and I'm trying to find out if this is a problem with the c-toxcore, or the clients.  It seems to work fine between qTox and my client though.

Anyhow, sending ytalk-like character by character is relatively easy, and I can demo it if anybody is interested but this isn't a change in the core protocol, it's a change in the client.  I'm coding under Linux, and I'm basing it off the echo_bot in the wiki.  I can only work with it during my time off.

I'll make a simple curses based client over time, then I'll move it up to probably QT later.  There's a lot of features I would like to add to the core - for example, I should be able to identify with the client if I'm connected P2P or to a relay, also identify the IP address when connected to either.

**Comment by anthonybilinski** [comment]
@mrwicks there's a work in progress protocol extension library that sounds well suited for this use case: https://github.com/toxext/toxext. Friends could optionally enable that protocol extension and when both are enabled have single-character messages, with clients being aware of the new message type so displaying them differently from full messages.

**Comment by mrwicks** [comment]
@anthonybilinski This sure is a fun protocol to work with!  I'll take a look at toxext.

One thing that is missing, and really needs to exist, is a way for one client to say "I support the following features" - this can be done under the hood actually with the c-toxcore library, since when you register call backs, the c-toxcore library can collect the information about what the client supports, and report that to the other c-toxcore lib on the other side.

Here's something **_I_** want to add - a file system.  FUSE is perfect for this.  If you've under Linux or Mac, check out sshfs if you've never used it.  It's wonderful.  It was written by the same guy that did FUSE.

Anyhow, I'm getting off topic, so I better shut up.  Thanks for the pointer.

**Comment by anthonybilinski** [comment]
> One thing that is missing, and really needs to exist, is a way for one client to say "I support the following features"

ToxExt gives exactly this functionality :D

Doing it directly in toxcore is definitely possible - but it means that toxcore would need to support an expanding list of high level features. It also means that negotiation of supported features would need to be added to the core protocol. Having them as external extensions is already supported in the protocol and allows faster adding of new features without having to touch the central network crypto library.

> Here's something I want to add - a file system.

uhh, to Tox? or just as a project in general?

**Comment by mrwicks** [comment]
> > Here's something I want to add - a file system.
> 
> uhh, to Tox? or just as a project in general?

To the c-tox core, as an option using FUSE.  With Windows (and probably android and iPhone) this may not be useful, but under Linux and Mac, it would allow you to mount a friend's file system as if it's a NAS.  The friend would determine what directories you have access to and what permissions you would have - maybe read only, maybe write as well - could be write only though that's a little bit of a trick.

With more primitive operating systems, like Windows, you'd still be able to copy and write to the file system, but it wouldn't be seamless like it would be under a Unix like OS.  It MIGHT be possible under Android and IOS, but frankly, I don't much care about them at this point in time, as I'm not very competent in coding them.

If you've never used it and you're on a Un*x system, try firing up SSHFS.  It's a simple, elegant way to connect to a remote computer as if it's a USB flash drive.  I use it all the time now.  My computer at work is mounted to my computer at home, and vice versa.  Does away with my need to use X2Go since both machines have nearly identical setups.

**Comment by zoff99** [comment]
@anthonybilinski @mrwicks 

> One thing that is missing, and really needs to exist, is a way for one client to say "I support the following features"

actually this is implemented in isotoxin and also in the development branch of toxcore already.
just nobody is merging it into master, for some unknown reason

**Comment by zugz** [comment]
* Tuesday, 2019-08-20 at 22:46 -0700 - mrwicks <notifications@github.com>:

>There's also additional overhead (every character = 1 packet!)

Yes, given the overheads I would have thought it would make more sense 
to gather multiple keystrokes into a single packet, with full timing 
information in the packet. It might take some experimentation to see how 
long the lag can be before it starts interfering with natural 
communication, but my guess would be that sending one packet per 250ms 
would be fine. So each of your keystrokes appears at the other end 
[250ms + network delay] after you type them (but should appear on your 
screen immediately).

Beyond that, I think classic unix talk clients had things figured out.

Participants be allowed to have different screen widths, so I recommend 
having logical lines of arbitrary length which are wrapped by the 
client. You can edit the current line only, with ^H/bkspace and ^W and 
^U understood correctly, terminated with ^M/^J.

I'd say a fixed-width font should be used by default (for ascii-art 
purposes), but I suppose this can be left to clients.

Anyway, as Anthony Bilinski says, this isn't really something which 
should go in toxcore itself. It looks like a perfect test case for 
toxext.

If you are interested in helping out on c-toxcore though, that would be 
great! Saying hello in #toktok on irc.freenode.net is probably the best 
way to get started.

**Comment by zoff99** [comment]
@mrwicks there is a public tox group chat aswell

**Comment by iphydf** [comment]
Nothing to add in the core library.
