### ISSUE TITLE
Proposal: c-tox core should indicate timeout when file transfers fail.

### ISSUE THREAD

**Issue by mrwicks** [TokTok/c-toxcore#1339]
When a file transfer fails, there is no (direct) way for a receiving client to see that it's failed - it just appears completed.  Normally on the completion of a file, the callback set by tox_callback_file_recv_chunk () will pass a chunk length of 0.  When a file transfer fails, the callback simply stops being called.

I would suggest that the callback to receive a position of 0, with a length of 0 after a timeout (perhaps 30 seconds?) within the c-toxcore protocol to indicate failure so the recipient realizes the file that was being received wasn't entirely received.

Otherwise, the client can implement this with an appropriate timeout, but I think it's best if the client's work is minimized.

**Comment by JFreegman** [comment]
A client has enough information about the file transfer to easily accomplish this:

```
main_loop() {
    for each ft in file_transfers {
        if (ft.last_chunk_size != 0 && timed_out(ft.time_last_received_chunk, TIMEOUT_INTERVAL)) {
           ft.abort(); 
        }
    }
}
```

To do this properly we would need to add additional config options so that clients can customize this behaviour (clients may not want timeouts, or may want something other than the default). I don't see any reason to add more complexity to an already complex API for the sake of saving clients a couple lines of code.
