### ISSUE TITLE
More security for Tox - A public key for each contact

### ISSUE THREAD

**Issue by wuniversales** [TokTok/c-toxcore#1363]
This would greatly increase the security of the application, it is a suggestion ...

If each contact has a public key, in case of being hacked, you would only understand the information of a user, you would not understand the information of all your users.

**Comment by sudden6** [comment]
Each ToxID contains a public key already and each connection between you and your friends uses a different encryption key. I think that's what you meant, right?

**Comment by wuniversales** [comment]
I mean a different public key for each contact.


For example, I have the public key "036156" for my friend Juan.
And have the public key "194618" for my friend Pepe.

So to speak, different public identities in each contact.

**Comment by sudden6** [comment]
So you speak about your own public key? You could use a different tox profile for each friend, that would achieve exactly what you want I think.

**Comment by wuniversales** [comment]
Yes, that's what I'm talking about, having a public key for each friend, that makes data hacking more difficult.
If for whatever reason, they find out the private key, they would only discover it for one of the contacts, not for all contacts, so only one conversation would be compromised ...

It's a little crazy, but I think it's better that way :)

I do not know if I have explained myself, in short, I say it to increase the security even more.

**Comment by Renha** [comment]
well the only sensible way they could get access to your private key is by accessing your computer. So all the other keys stored there would be also compromised.

**Comment by sudden6** [comment]
@wuniversales I don't think that makes sense, because as @Renha said, all of the private keys would be stored in the same file, encrypted by the same password.

If you still want that for yourself, just create multiple profiles with different passwords, but this is not realistic as a default mode of operation.

**Comment by wuniversales** [comment]
I am almost certain that the nsa has some kind of tool to decrypt encrypted communications.
By encapsulating each conversation with different public IPs, decryption of the conversations can be made more difficult. do not?

**Comment by Klagio** [comment]
> I am almost certain that the nsa has some kind of tool to decrypt encrypted communications.
> By encapsulating each conversation with different public IPs, decryption of the conversations can be made more difficult. do not?

Hi by connecting, before the cakk, to the Tor network (in Android with Orbot) would that make it impossible to decrypt a message or voice call?

**Comment by iphydf** [comment]
NSA is not currently able to break the NaCl encryption we're using. It may be able to in the future, but at that point, multiple long term secret keys (tox addresses) won't be additional protection. We already use a different encryption key per contact, so that's roughly the amount of protection you're likely to have for the foreseeable future.
