### ISSUE TITLE
Hosting a Server to establish connections and be always able to recieve messages

### ISSUE THREAD

**Issue by Gladox114** [TokTok/c-toxcore#1627]
My suggestion is to be able to make a server. Using something like a Raspberry pi or a second phone sitting in some corner or on a PC.

This would fix a ton of things like:
1. With this, phones could survive longer because many are complaining that it drains a ton of energy.
2. People who rarely come online could miss connections they would need to message someone or get friend requests.
3. Maybe there aren't a ton of things

If you go outside you can connect to your server with a VPN (Host one or use something like ZeroTier(OpenSource))

Problem would be if the Raspberry pi as examble stores everything unencrypted you could get physical access to it easily or someone who hosts it could maybe get some access so this needs to be water proof?

**Comment by zoff99** [comment]
@Gladox114 something like this exists:

https://github.com/zoff99/ToxProxy

**Comment by Nokia808** [comment]
@Gladox114 
Hi. Your suggestion is almost the same of already existing project ! Your idea is already executed by some one - see:
https://github.com/envsh/tox-homeserver

However, this project is dead as I think because developer show no response - see:
https://github.com/envsh/tox-homeserver/issues/14

Moreover, this approach MUST be fully OPTIONAL because it undermine the nature & aim of Tox protocol which created to be serverless chat/messenger protocol ...

**Comment by iphydf** [comment]
Tox proxy can be done outside of toxcore.
