### ISSUE TITLE
Can you have channels like on Discord?

### ISSUE THREAD

**Issue by Joe23232** [TokTok/c-toxcore#1666]
Can you have channels like on Discord?

**Comment by hardhub** [comment]
Discord is not secure. Issue can be closed.

**Comment by stikonas** [comment]
> Discord is not secure. Issue can be closed.

My reading of the issue is that it was requested to have similar thing on tox. But it's a bit ambiguous.

**Comment by hardhub** [comment]
> 
> 
> > Discord is not secure. Issue can be closed.
> 
> My reading of the issue is that it was requested to have similar thing on tox, so whether Discord is secure or not it doesn't matter if the feature in tox is implemented securely. But original request is indeed a bit ambiguous.

I mentioned that discord cannot be considered as example. IMHO - In general!
And of course I do not see any feature request explaining what exactly user wants in tox.  
Also it is not clear what should developer do if he does not use discord?   
Install it just because some Joe wants something abstract?

So yes FR is not specified well. But I am trying to say we cannot consider any insecure shitware when discussing tox in general.

**Comment by Goddard** [comment]
Is it related to this doc?
https://github.com/TokTok/c-toxcore/blob/ngc/docs/DHT-Group-Chats.md

**Comment by iphydf** [comment]
Tox already has private group chats that require invites, and is getting new DHT-based public group chats.
