### ISSUE TITLE
I have a repository ?

### ISSUE THREAD

**Issue by DataMaster-2501** [TokTok/c-toxcore#1681]
I'm on **kUbuntu 20.04 LTS**
and the last update on the Ubuntu repo is **v0.2.10-1build2**.
I would like to know when would v0.2.12 or newer be added to the repo?

**Comment by nurupo** [comment]
Please ask this question to whoever maintains the toxcore package in Ubuntu. We don't maintain the package in Ubuntu.

**Comment by DataMaster-2501** [comment]
Well that's lame that you don't maintain the package on Ubuntu.😞
I would think you want as many people using Tox as you can get.😒 
Maybe that is why Tox is dying a slow death. 🙄
I will try to contact the person who maintains the package on Ubuntu.
thanks for replying.

**Comment by nurupo** [comment]
I'm not sure why you had the expectation of us maintaining packages in various Linux distributions in the first place. It sounds like you have some sort of misunderstanding of how packaging on Linux works. It's usually up to distribution's packagers to package the software, not the developers of the said software. If you check who maintains packages in a distribution, you would quickly notice this. For example, in Debian, the Chromium package is not maintained by the Chromium developers, the VLC package is not maintained by the VLC developers, etc. Well, it's certainly not unheard of for software developers to also double as packagers of their software, but it's more of an exception than a norm. In any case, the appropriate channel to report issues such as this, issues with how a package is packaged in a distribution, is the distribution's package bug tracker, so that the package maintainer would see the issue, not the upstream (this) bug tracker, where you contact the developers of the software.

Well, I hope you have learned something!

**Comment by DataMaster-2501** [comment]
but you are forgetting that there are many app developers that do maintain the package on Ubuntu/Debian/Arch & the one's that don't seem illogical to me.
Don't you want as many people using tox as you can get?
if yes than you would want to make it available to as many people as you can.
I stand by this line
"Maybe that is why Tox is dying a slow death." (in the end we will see)

"Well, it's certainly not unheard of for software developers to also double as packagers of their software, but it's more of an exception than a norm. " 😒

Well maybe it's time for it to become the "norm"

I mean why make something if no one ends up using it,
seems pointless if you ask me.

**Comment by anthonybilinski** [comment]
You're using an LTS distro. The entire purpose of LTS is for long term stability, taking only security fixes and select bug fixes, and not taking every patch update from developers. This wouldn't be different if the package was maintained by developers instead of distro package maintainers. If you want more up to date packages, you could update to kubuntu 20.10 which has toxcore 0.2.12, and if you want even more updated packages you can use Arch or some other rolling distro that takes updates soon after they become available.

It's ridiculous to imply that tox developers not maintaining a kubuntu package means they don't care about tox or don't want people to use it. nurupo specifically has done a lot on the user delivery side of many tox projects.

**Comment by DataMaster-2501** [comment]
Well we will have to agree to disagree.
I have voiced my opinion & I stand by it.
I can only hope better devs one day fork this project.
