### ISSUE TITLE
Move repository to Tox organization

### ISSUE THREAD

**Issue by ovalseven8** [TokTok/c-toxcore#191]

**Comment by iphydf** [comment]
I think moving to the Tox organisation would not be beneficial to any cause at this time.

Currently, there are strong technical reasons to keep all the repos we as the toktok project are working on in the single organisations:
- Easier to write tooling to help us manage pull requests and issues (e.g. https://github.com/iphydf/pull-status).
- Easier to keep all repository settings up to date.
- No need to synchronise teams, so e.g. the Contributors team in toktok would need to be replicated in the Tox org. Someone would need to keep this up to date, or write a continuous service/cronjob to synchronise the two.
- Quick overview of all our managed repositories in Travis, Github, and Coveralls.

Generally: convention enables better tooling and simplified management.

Moving this repository alone into the Tox org would mean a lot of administrative overhead I don't have time for. If someone volunteers to keep an eye on changes, and makes sure that any change to e.g. the Contributors group in toktok is reflected in Tox within a few minutes, I'm happy to talk about the possibility of moving. If not, then a move will mean move + fork, since I have a goal and limited time, so I'm actively working to reduce management overhead, not increase it.

Do you have strong reasons for wanting this that outweigh the benefits of keeping the status quo?
