### ISSUE TITLE
ToxAV is still on the old API style

### ISSUE THREAD

**Issue by GrayHatter** [TokTok/c-toxcore#203]

**Comment by iphydf** [comment]
Can you provide additional context? What is the old API style, what is the new style?

**Comment by nurupo** [comment]
I think it's a reminder that toxav is not using stateless callbacks, since we have revented the commit for that. grayhatter said that he knows what causes the issue in the stateless to avoid commit, but the fix for it looked like too much work for him to do, so "help needed". Would be useful if he could explain here what exactly causes the issue in that commit.

**Comment by iphydf** [comment]
Ok, so a sub-issue of #40. Just making sure that's referenced here (I wish github had issue dependencies.. or just about any other feature of a good bug tracker).

**Comment by alexeysvrv** [comment]
@mannol You can help with this?

**Comment by iphydf** [comment]
The assigned milestone is v0.0.3. Can we get this done by then? v0.1.0 is somewhat pressing, so I'm tempted to push this to v0.2.0, which constitutes another API break.

**Comment by GrayHatter** [comment]
@iphydf there's no timeline set for v0.0.3. Perhaps I misassigned this, and should have chosen v0.1.0 But I'm unaware of the reasoning to be pushing for a quick v0.1 release.  Is there any benefit to that?

I've just been tagging them according to my own arbitrary priority level, and by difficulty.

**Comment by iphydf** [comment]
ToxAV is now on the new API style. But: we'll make yet another new API style :).
