### ISSUE TITLE
Contacts are shown offline after being idle for some time (networking issue)

### ISSUE THREAD

**Issue by ovalseven8** [TokTok/c-toxcore#231]
The user @yurivict reported (https://github.com/irungentoo/toxcore/issues/1550):
> After talking to users and then being myself idle for many hours I came back to see all users offline. But after qtox restart users showed with online statuses. For some reason qtox stopped updating user status, so it created the false impression that everybody is offline.
> 
> Reporting it here because it appears to me the toxcore problem, and not a qtox problem.
> 
> qTox-1.3.0
> toxcore-0.151112_1
> FreeBSD

@GrayHatter [wrote](https://github.com/irungentoo/toxcore/issues/1550#issuecomment-197665328):
> Can reproduce in µTox. seems to happen if the internet connection is down for an extended time.

**Comment by zetok** [comment]
NB: In TCP-only mode problem is not limited to contacts that have been shown as online going offline, but all contacts are affected, regardless of whether they have or haven't managed to connect before.

I.e. some contacts that are online are shown as offline.

Dunno if behavior is the same with UDP on, since tox with it doesn't work (#440).

**Comment by iphydf** [comment]
Reopen this if it's still an issue. A number of improvements have happened since this issue was opened.
