### ISSUE TITLE
Contacts are shown offline when they are online

### ISSUE THREAD

**Issue by ovalseven8** [TokTok/c-toxcore#237]
Very important and old issue!

Because it's more clearer to read, just the link to the issue: https://github.com/irungentoo/toxcore/issues/1349

**Comment by sagb** [comment]
I wonder is it something special with our setup/connection, or everybody is affected and just ignore this or don't run tox client long enough?

**Comment by tormit** [comment]
Same problem, but only on OSX Yosemite. uTox 0.9.7
Contacts randomly online/offline.

**Comment by vladimiry** [comment]
This is a major issue in my opinion. It stops me from using Tox as a primary communication tool.

More related issues:
- https://github.com/qTox/qTox/issues/1315
- https://github.com/qTox/qTox/issues/1560
- https://github.com/qTox/qTox/issues/2820
- https://github.com/qTox/qTox/issues/2542

**Comment by alexeysvrv** [comment]
Guys, I propose to change the milestone of 0.1. This is a serious bug that requires a lot of attention

**Comment by iphydf** [comment]
0.1 is the API stability milestone. We need to get all the API changes done by then. We can make this a 0.1.1 target.

**Comment by TETYYS** [comment]
So is it impossible to debug or something? Why is this so long-standing?

**Comment by Ghosthree3** [comment]
I've noticed this happening to me when I start abusing my internet. I think the connection to the node just lags out and never tries to do anything about it. Moved my client (toxic) to a vps and haven't had an issue since.

**Comment by githubbantor** [comment]
Can reproduce on latest qTox.

**Comment by fcore117** [comment]
Affects me with uTox too. Some contacts are offline until i exit uTox and start again.

**Comment by antis81** [comment]
On Toxer I had a few investigations:

1. **After** a successful bootstrap, the friend status (not the connection state) is initialized from the state file, which seems wrong. This should not be saved at all.
2. The connection status is correctly initialized on start by requesting the actual state.
3. Now `tox_friend_get_connection_status` returns **always** `TOX_CONNECTION::NONE` ->  disconnected, even when connected.
4. After implementing the event system and the callback, this will change now after some seconds and looks good to me for the moment.

Please bare in mind Toxer is still WIP, but as I/we closely follow the API, it is a very good reference to investigate the problem. See this branch: https://gitlab.com/antis81/Toxer/commits/notifications

This is what it looks like:

1. Friends directly after loading the profile (older screenshot without local user information):
![toxer-friends-view](https://cloud.githubusercontent.com/assets/440517/23191549/88ac9f92-f89e-11e6-88c5-6e63c40f91c7.png)

2. Few seconds later:
![toxer-friend-status](https://cloud.githubusercontent.com/assets/440517/23191580/b0d8a7cc-f89e-11e6-9a9c-7b940d9002af.png)

As there is no official build instructions yet, here's a short one:
* CMake >= 3.5 (you can use 3.2 and lower the minimum requirement in CMakeLists.txt)
* Qt >= 5.6.1-1 (LTS release)
* c-toxcore >= 0.1.3
* Before compiling the first time, execute `scripts/getToxCore.sh` (links to system libs though, thus a dummy right now)

Build like usual CMake program:
```bash
cd /path/to/Toxer
mkdir build && cd build
cmake ..
make
```

**Comment by holesond** [comment]
In my case, I have noticed this "all friends offline" behavior happening quite often on uTox 0.9.7. However, older versions from 2015 like 0.2.0 or 0.3.2 (almost) never have this issue. Thus I have essentially switched myself (and many my contacts) back to uTox versions 0.2.0 or 0.3.2 (whatever version of these two we have available in static binaries or can compile from the source) in order to be able to communicate reasonably. I run most of the time Windows uTox-Linux uTox communication. 

Please note that voice calls do not work between uTox versions 0.9.7-0.3.2 or 0.9.7-0.2.0, likely due to protocol incompatibility. The good think is that one can at least chat when the two people have too different uTox versions. Surprisingly, running the older uTox client(s) to first locate your peers and then immediately switching to 0.9.7 enables peer detection in 0.9.7 as well as regular communication at least for 20 minutes. (A running voice call then typically terminates by itself after 30-60 minutes and one needs to run the old clients again.)

I hope this helps to shed some light on the issue.

**Comment by robinlinden** [comment]
Might have been fixed as part of onion pinging changes in #542
