### ISSUE TITLE
Add an option to make toxcore use a test network

### ISSUE THREAD

**Issue by iphydf** [TokTok/c-toxcore#246]
This could either be a compile time option or a runtime option that performs some translation of the basic network packet kinds (the `NET_PACKET_TYPE` enumeration defined in  `toxcore/network.h`).

It would allow us to run a stable production network in parallel with a testing network. The stable network would be used by most users, while the test network can be broken sometimes and we can use it to experiment with new features (like new-group-chats). If it's a runtime option, it would be a boolean in `Tox_Options` and users could switch networks in their client. It would also be easier to run a bootstrap node supporting both networks in the same executable.

**Comment by SkyzohKey** [comment]
Would this mean there would be 2 Tox DHT then ?

**Comment by Impyy** [comment]
@SkyzohKey Yes.

**Comment by SkyzohKey** [comment]
@Impyy looks nice so, could permits to do API breaks more easily without impacting end-users, you have my vote :+1:

**Comment by GrayHatter** [comment]
> Would this mean there would be 2 Tox DHT then ?

@SkyzohKey no. Only one DHT with two different "versions" of tox using it. So that if you're testing new features, fixes, other. You can only talk with other toxens using the testing version.

**Comment by iphydf** [comment]
Yes, it would practically be two DHTs. They would use the same port range, but all the packet IDs would be different, so if you're on the test network, you simply ignore any production network packets, and vice versa.

**Comment by GrayHatter** [comment]
I'm confused 

> It would also be easier to run a bootstrap node supporting both networks in the same executable.

If your node can support both networks, how is it two different DHT nets? If a bootstrap node can answer requests from both the testing network, and the production network. Unless they're using separate buckets, it'd be the same network, just acting differently.

And if you're using separate buckets, why would you want to bind to the same ports, if you're trying to keep the nets that separate, make them fully separate. Otherwise what's the gain?

**Comment by iphydf** [comment]
Let's not do this after all. It's a bit of complexity we don't need right now.
