### ISSUE TITLE
Put the IRC channel in the README

### ISSUE THREAD

**Issue by emdee-is** [TokTok/c-toxcore#2463]
You want to encourage users of Tox, so put the IRC channel in the README.

I know the channel on libera is not very alive, but it is not defunct, contrary to rumours of its demise: https://github.com/TokTok/c-toxcore/pull/2456
Do you really want to remove the only public users forum for discussion on Tox?

I know the IRC channel is not lively, but it is alive, and it was bi-directionally gatewayed into the Tox-Dev NGC. The IRC should be kept alive in case there are users, or potential users. It is expected that an opensource software package has an IRC channel to help users, and it was a good place for lurking former/retired/paused developers to keep an eye on things.

Instead of abandoning the IRC and truncating the meagre documentation, I think we should keep IRC alive, and respond to users, or maybe even potential users. And some of us have Tox<->IRC bridges as software we are developing, so it's useful to have an active IRC group.

JF said there were problems with the libera staff, and if that's the case, we should look at moving the group, not abandonning it. You need opensource projects to be visibly supported on IRC; the channel helped me a lot when I was getting started, and had a much broader audience than the dev NGC.

There's a good alternative at https://www.oftc.net/ I think. Good security and helpful staff; they have good support for IRC with security over Tor which not all IRCs do (and it's not easy).

Does anyone know who setup the IRC on libera? Could they look at moving the group to oftc.net and leaving a banner message on libera to say it's moved?

**Comment by emdee-is** [comment]
As an enduser, I can vouch for oftc.net; helpful staff on IRC and a good setup to do security with SSL and individual certs over Tor (not easy, but scriptable access).

I think it's really important to have IRC so that we're visible, and so we can help new users with teething problems, and some people prefer it. If there are problems with libera, let's just move.  

@nurupo @iphydf @robinlinden  do you know who set up the IRC on libera?

**Comment by emdee-is** [comment]
I suggest interested people to get an account on oftc.net to try them out, and let us know about any dealings with the staff. Mine were getting their certs-and-Tor setup working, and they were good  and helpful.

**Comment by JFreegman** [comment]
Directing people towards a server that we know to be run by unethical people is unethical in itself. Moreover, moving to another server doesn't address the underlying problems:

- The possibility of spying on users' communications shouldn't be a feature of the architecture. This obviously goes for private conversations, but also for group chats, as users should not have to worry about people outside of the group reading their conversations without the consent of anyone in the channel. Just as we shouldn't have to worry about our living room being bugged, so too should we not have to worry about this with our online groups. 
- Relying on strangers for our communication infrastructure and putting blind faith in their good will is undesirable, as we've learned the hard way twice now
- Using a service that doesn't use encryption by default and has no other option than an inherently flawed encryption scheme is highly problematic (client-server, authority based). This alone is enough reason to stay off IRC. 

This community has created a solution to all of these problems. We're presently using that solution for the majority of our development discussions, and everyone is free to join us. The only thing the community lacks is intuitive and fully functional clients (I hesitantly admit that Toxic is not so user-friendly). That however is not a toxcore issue.

To address the issue of potential new users and people who might be looking for us in IRC, what we should be doing is maintaining our channels in libera and directing them towards the Tox development group. If there aren't already instructions in the topic, there should be. If newcomers aren't able or willing to use the software that they ostensibly want to contribute to despite being given all the tools to do so, they probably wouldn't be able to contribute in a meaningful way in the first place.

This is the last I'm going to say on this topic, unless someone can give a legitimate technical reason why they (or newcomers) are unable to join the Tox groupchat, in which case we should focus on resolving it rather than sweeping it under the rug. I recall @nurupo once mentioned that he wasn't able to use a bouncer in Tox, however that issue could be resolved by running a Toxic instance on a remote server that the bouncer would typically be run on (which is something I do myself). Also, someone could easily write a proper bouncer.

**Comment by emdee-is** [comment]
AFAIK No one has asked Libera for their side of the story: did you?
One side of the story is not sufficient as you may not know but there has been
a lot of censorship laws put in place for CovID. E.g. Rumble, a Canadian company, simply stopped providing services in some European countries because of what their governments demanded they do in terms of censorship, in Canada. For all we know, some of Libera's actions may have been dictated by law - you would have to ask Libera for their side of the story for us to know.

Laudably woke as your sentiment is, no one on #Toktok seems to agree the argument is relevant to a public channel like #TokTok. And @nurupo  who set up #TokTok, was very generous with his time and we chatted at length about moving; he said that it was a considerable amount of work to setup a channel,
then move all the users, and didn't see the point. I agree. As for your one-
developer boycott of Libera, methinks thou doth protest too much.

I had wanted your NGC gatewayed like it used to be, which was convenient,
and helped show the world via IRC that Tox is active.  However, it might be
better if we didn't; #TokTok has always been very civil. Those who want can
easily do both, or can start a NGC group of their own. I'm glad you've
had your last word to say: let's ask @iphydf  what he wants to do.

Finally, you submitted a PR based on false premises, over objections raised
in the PR  that deleted the IRC channel from the project README. In PR you said that #TokTok was defunct, which is obviously untrue; it seems there are a significant number of developers that don't want to join your NGC. And you claimed that everyone can move over from #TokTok to your NGC group which is absurd: #TokTok's most important role is to encourage new users to get started, and to help them in the beginning - as it did for me: you can't help users who are having trouble connecting with a connected NGC.

 #TokTok's role in IRC is essential and expected in the FOSS world: I call for the PR to be reverted as it was based on untruths.

**Comment by JFreegman** [comment]
>AFAIK No one has asked Libera for their side of the story: did you?

We did indeed ask Libera for their side of the story, numerous times, and were met with gas lighting, insults, and logically inconsistent excuses. I mention this not for you, but for anyone else who might be reading this.

> As for your one-developer boycott of Libera, methinks thou doth protest too much.

I'm not in charge of the TokTok repository and I don't have the final say in these matters. I'm also not the one who shut down the relay bot, nor did I twist anyone's arm to shut it down. All commits in the c-toxcore repo have to be approved by other admins, and can be blocked by any other admin; it was a collective decision.

Methinks thou doth protest too much. Let it go.

**Comment by Chiitoo** [comment]
> We did indeed ask Libera for their side of the story, numerous times, and were met with gas lighting, insults, and logically inconsistent excuses. I mention this not for you, but for anyone else who might be reading this.

It would be good to have more of this out in the open I think.  Going by some of the comments I've seen, and since Libera does say "Libera Chat does not collect or log private or public IRC messages" [1], they sure seem to not be following that policy.

As for the actual request here, I too would like the Libera channel to be mentioned still too, as it is the channel I use instead of the Tox group chats.  (Not that I've been very active with regards to development and things... hoping that will one day change!).

1. https://libera.chat/privacy/

**Comment by emdee-is** [comment]
> > We did indeed ask Libera for their side of the story, numerous times, and were met with gas lighting, insults, and logically inconsistent excuses. I mention this not for you, but for anyone else who might be reading this.

So you say, but did you or anyone else file a complaint ["by contacting policy@libera.chat."](https://libera.chat/privacy/) or with [IMY](https://www.imy.se/en/)? Unless you do, it's just your impression of conversations with people that may not even have been employees of the company, and without us having heard their side of the story.

> It would be good to have more of this out in the open I think. Going by some of the comments I've seen, and since Libera does say "Libera Chat does not collect or log private or public IRC messages" [1], they sure seem to not be following that policy.
There are a lot of the developers that don't join that NGC group and only use the #TokTok channel, and it's needed anyway to attract and help beginners. Taking it out of the README just sabotages the project.
 
> As for the actual request here, I too would like the Libera channel to be mentioned still too, as it is the channel I use instead of the Tox group chats. (Not that I've been very active with regards to development and things... hoping that will one day change!).

JF wrote "All commits in the c-toxcore repo have to be approved by other admins, and can be blocked by any other admin" but he's being parsimonious with the truth here: he closed this issue as completed without it being completed, not even waiting to see what @iphydf wanted to do, as I had suggested.

Ths can happen because the project does no project planning and prioritization https://github.com/TokTok/c-toxcore/issues/2584#issuecomment-1925924797
