### ISSUE TITLE
What are your plans for updating the release?

### ISSUE THREAD

**Issue by SergeyDjam** [TokTok/c-toxcore#2500]
Hi!  Toxic released release 0.13 on the main branch. There were no releases for 2 years. Perhaps it makes sense to release 0.2.19?

**Comment by iphydf** [comment]
https://github.com/TokTok/c-toxcore/milestone/48

Toxic has made the decision to release against an unreleased version of toxcore. Since that unreleased version has unfinished savefile code in it, we now need to do some extra work to produce backwards-compatible savefile code with that unreleased savefile code. If we don't do that, all DHT-based groups ("new group chats") owned by Toxic users will at least lose their owner and possibly break down completely (not very likely, unless many people upgrade all at once, but still they will 100% lose their owner, because the owner will lose the secret key). Hence, we are now working on that backwards compatibility code.

**Comment by iphydf** [comment]
Once we make the release, move this ticket to z-meta and close it.

**Comment by robinlinden** [comment]
Release is released.
