### ISSUE TITLE
Add option to disable UDP hole punching

### ISSUE THREAD

**Issue by iphydf** [TokTok/c-toxcore#254]
Ideally, we would have the existing UDP hole punching as a "technology" choice (see #226). If we can selectively disable hole punching, it's much easier to test whether uPNP or NAT-PMP actually work. If hole punching is always enabled, then uPNP or NAT-PMP might not work but we wouldn't easily know, because hole punching would still find us a forwarded port.

**Comment by nurupo** [comment]
@iphydf it's a good idea to be able to disable hole punching for us to test whether UPNP and NAT-PMP work, but do we really want to expose ability to disable the hole punching in the public API if all we want is to test if some PR works or not?

Also, I would imagine that for Tox with hole punching disabled to work, both peers need to have port forwarding set up, because you not only hole punch your own NAT, you also hole punch others' NAT. This probably should be considered during the testing,

**Comment by iphydf** [comment]
Pushing to v0.0.5 for reasons described in #262.
