### ISSUE TITLE
Strange checks in Messenger.c

### ISSUE THREAD

**Issue by Mikhael-Danilov** [TokTok/c-toxcore#352]
Consider https://github.com/TokTok/c-toxcore/blob/master/toxcore/Messenger.h#L39
`#define MAX_CONCURRENT_FILE_PIPES 256`

Following conditions is always false:

- https://github.com/TokTok/c-toxcore/blob/master/toxcore/Messenger.c#L2214
- https://github.com/TokTok/c-toxcore/blob/master/toxcore/Messenger.c#L2274
- https://github.com/TokTok/c-toxcore/blob/master/toxcore/Messenger.c#L2292

all of them something like:
```
            uint8_t filenumber = data[0];

            if (filenumber >= MAX_CONCURRENT_FILE_PIPES) {
                break;
            }
```

**Comment by iphydf** [comment]
I've asked @irungentoo about this before, and the reason for this to be there is that `MAX_CONCURRENT_FILE_PIPES` could become less than `UINT8_MAX` at some point, and then the code would still work.

To avoid the warning, we currently simply disable it in compiler flags (not great). To fix it, you could do one of these things:
- Surround with `#if MAX_CONCURRENT_FILE_PIPES < UINT8_MAX` (ew).
- Make `MAX_CONCURRENT_FILE_PIPES` a smaller number.
- Cast `filenumber` to `unsigned int` or `uint16_t` or some other larger unsigned integer type.

So far, I didn't really like any of these, so I haven't touched it. What's your suggestion?

**Comment by GrayHatter** [comment]
255, problem solved?

**Comment by iphydf** [comment]
@GrayHatter if we do that, we'll open a beautiful security vulnerability. There will probably be no static analysers (apart from sound ones that can't work on toxcore) that would ever find it. @zetok would probably find it through testing, though.

Hint: If the number is 255 instead of 256, I can cause arbitrary code execution using any regular tox client by sending a lot of files and then starting a toxav session. I can do it faster by crafting a packet myself.

**Comment by iphydf** [comment]
I take it back, it would still be safe :).
