### ISSUE TITLE
Autotools doesn't install cmake stuff

### ISSUE THREAD

**Issue by Diadlo** [TokTok/c-toxcore#360]
Autotools doesn't install cmake stuff.
Commit hash: a096c71db867ac83fc3e01e0fbe98573d20f9286

**Steps to reproduce**
1. Build toxcore using autotools
2. Install toxcore
3. `pkg-config --libs toxcore`

Output is `Package toxcore was not found in the pkg-config search path.`

**Comment by jin-eld** [comment]
Actually autoconf is installing libtoxcore.pc as it has always been doing, I do wonder why this was duplicated by cmake with a pkg-config configuration that uses toxcore instead of libtoxcore and, from what I can see the two configs are also not in sync.

Both build systems should use the same .pc.in files.

@iphydf what was the purpose of duplicating the .pc files? I see your  old/new clients comment in commit b14b8d07facba8564a37e6dd2a346f0e490de89d, but imho it does not really make sense to produce two "same" pkg-configs for one library...

Which configs are considered "current"/"default"?

**Comment by iphydf** [comment]
The `toxcore.pc` file is incompatible with `libtoxcore.pc` file. Because of this, I used a different name (`toxcore`). Now, there are a lot of clients that use `libtoxcore` but I want to move away from autotools, so in the transitional period, there has to be a `libtoxcore.pc` file created by cmake that is compatible with the autotools generated one.

**Comment by jin-eld** [comment]
Why is it incompatible? Why would the clients even care if the tox library was compiled with cmake or autotools?

Apart from that, sad to hear that you're dropping autotools support.

**Comment by iphydf** [comment]
We're only dropping autotools support once it becomes a maintenance burden. At the moment, it's not, so we'll keep it around.

Indeed, users should not care what it's compiled with, and that's why I added the compatibility files. The new `toxcore.pc` is incompatible with the old `libtoxcore.pc`. The cmake `libtoxcore.pc` should be compatible with the autotools one.

**Comment by jin-eld** [comment]
So what exactly was the incompatibility?

From your description I take it that this issue should be fixed in the cmake part?

As I wrote earlier, both build systems should process the same *toxcore.pc.in file, there should not be copies of it, you just have to decide which one you would like to keep around...

**Comment by Diadlo** [comment]
Seems, issue will fixed when autotools support will be fully dropped. Then I'm closing it
