### ISSUE TITLE
[discussion] Future of the project

### ISSUE THREAD

**Issue by alexeysvrv** [TokTok/c-toxcore#476]
Guys, let's decide how we will continue to develop. I understand that there is a development roadmap. It is relevant, but there is no internal organization and coordination. Those questions that are marked high priority is not being release is often tolerated. Need understanding and persistent movement toward the goal. To write a new Protocol is not easy, but we've been doing this for 4 years... Too many. There are many fundamental problems of the Protocol, such as simultaneous work on multiple devices simultaneously, offline messages and more. But it is solved. There is a platform ready that can be used as solutions for a particular issue.
 In my opinion, the project needs a coordinator, the Manager, who will lead a team and help. Also need experts in cryptography and security, key programmers, the person responsible for the packaging and infrastructure. For more incentive, we can arrange groundpounding of the company.
Ready to nominate his candidacy for the post of project coordinator. Yes, I am an ordinary user and do not understand programming, but I'm a responsible attitude to work.
 Let's forget the infighting.
What do you say? @iphydf @irungentoo @JFreegman @grayhatter @nurupo @mannol

**Comment by pranomostro** [comment]
I do not think that a top-down structure would benefit this project.
But if the maintainers are okay with that...

**Comment by SkyzohKey** [comment]
We should setup a Mattermost/Discord/Slack channel for developers first. Tox already had a top-down structure and it didn't benefited it. cf. @stq money stealer.

**Comment by alexeysvrv** [comment]
You may be right. But we need organization and cooperation. I agree about the communication channel. And one ought not to equate all with the same brush. If you stole one, it does not mean that will steal the other. I just want the project to live and thrive. @SkyzohKey @pranomostro

**Comment by robinlinden** [comment]
@SkyzohKey Edited your comment as you were highlighting the wrong user, also let's try not to go there.

**Comment by pranomostro** [comment]
I am not nearly as active here as I should be, therefore I have no word in anything.

**Comment by optimumtact** [comment]
I disagree on the chat clients suggested as they are not open source, rocketchat is one example, but I myself still prefer irc for developer focused projects.

**Comment by GrayHatter** [comment]
> I am not nearly as active here as I should be, therefore I have no right to an opinion about the direction of the project.

I disagree, I want more opinions from more people (well, rational people) who are not necessarily the primary developers. Anyone can reject bad ideas, that's easy. The hard, and important one, is making sure you hear and consider as many ideas as you can.

**Comment by nuclearcanary** [comment]
I am one of those not in the primary development group. I have been watching from the fringes for a while, and built a couple of proof of concept apps. But the instability has kept me from going full tilt into it. I would love to contribute, so a road map would be good for me to plan some contributions. I would not mind a complete overhaul of the protocol as long as this one was clearly documented.

So in summary, Organization Structure, Road map, Protocol Revamp and Documentation get my vote.

**Comment by SkyzohKey** [comment]
>I disagree on the chat clients suggested as they are not open source, rocketchat is one example of a similar project but open source.

Mattermost is open-source and federated, eh.

Anyway, we'd need something better than IRC that really integrates with software dev' (not irc bots...) to make it easier for (newers?) contributors to participate and make Tox even more awesome.

**Comment by alexeysvrv** [comment]
Guys, please, Express your opinion on the matter. It is important to have representation from as many people. Thank you

**Comment by zoff99** [comment]
toxcore beeing more mobile aware / mobile friendly is the top priority for me.
and i guess needs to be top priority for more users to get on board.

**Comment by zugz** [comment]
I'm also a new contributor, so weigh my opinion accordingly, but to my
mind the main task to concentrate on for now is documentation. In order
to sensibly discuss non-trivial changes, we need a clear and complete
account of the protocol which c-toxcore implements. The spec we have is
a good start, but it isn't complete and it could be much clearer. I've
been working on the DHT part of this on hs-toxcore as part of the
process of developing a haskell implementation; having a relatively
readable and easily adjustable implementation in haskell/rust will
hopefully also be very helpful, but work on the spec can be done
separately from and before work on reimplementation.

Once the relevant documentation is in place, I think we should think
carefully about bandwidth-optimisation. My impression is that network
usage could be reduced a lot even without any breaking change to the
protocol. Hopefully this will also help with the problems on mobile
phones.

I don't like the idea of wasting energy and risking splits by trying to
use an alternative to irc.

**Comment by throwaway217** [comment]
Normal user here.
The fact that is has so many front ends is a blessing in a world where every secure chat desktop application is based on electron. From what I see offline messages are? planned for toxcore 0.4, getting them earlier would probably bring a lot of attention to the project. It might also solve the problem on mobile, since instead of running the whole application the whole time you can get around this with a wrapper that automatically starts and closes tox every x minutes to check for messages, pipes them to notificaion thingy and then when the user interacts with it tox is opened again and after he doesn't send or receive a message for x minutes, tox closes automatically.

**Comment by yurivict** [comment]
> every secure chat desktop application is based on electron

Electron is based on nodejs which takes code directly from github, and doesn't sign downloads. This makes electron vulnerable to MITM attacks and github account takeovers. So Electron-based software can't be secure.

**Comment by alexeysvrv** [comment]
Electron popular, but not necessary. Let customers develop their course...

**Comment by im-grey** [comment]
Normal user here.
Security should and ease of use be the top most things, and Tox software should have a singular public face.

Any time I bring up Tox to non technical people, they just want to know if it's more easy to install and use than Facetime/Skype. Any time I bring up Tox to technical people, they bring up security issues. If it's not just as easy for more easy to use than Facetime and Skype than normal people have no reason to use it. If it's not more secure than WebRTC/Wire/Jitsi/other centralized things then technical people have no reason to use it. 

As for the public face, "clients" do not make any sense to normal people. Normal people don't know what the web is, or what an application is, or difference is. Normal people don't know what a server is, or what that means for it to be down. They don't know what a client is, or mean it means for a client to not be able to connect to anything. Having multiple clients is awesome and I hope people keep making them. Though to present themselves to the public Tox should have a singular "official" face. Downloading "antidote" on their iPhone and "qTox" on their Macbook makes no sense to normal people. They'll think it's two entirely different apps made be competing corporations. I know this because I have tried it. I love uTox, I like RaTox and Toxic a lot. But I think qTox should just be "Tox for computers" and Antidote and AnTox need to be renamed "Tox for smartphones." Nerds like me will always be able to look at the wiki/Github and find obscure of specialized clients for our own nerdy needs. Normal people need to be spoonfed. I know this because of the job I work. This is all boring marketing stuff, but this is how one gets powerful crypto into the hands of everyday people. 

I think organizing better is good, and setting up a Mattermost is good too. But Tox devs have a bad history with communicating with people interesting in using it or watching it grow. Switching to a private room type of thing would cut those people out entirely, I think. But I have not used Mattermost before. Don't use Dischord/Slack or proprietary things like that. Not that the type of people to develop an encrypted, decentralized Skype replacement would use things like that.

I want Tox to win. I don't know C/C++ so I can't really help. When there is a more finished product worth showing to the public, I want to help with advertising, if I can. I don't know what else I can do, I just know I want Tox to succeed.

**Comment by alexeysvrv** [comment]
Hey. Say, Tox is dead or not? Since Irungentoo ceased to participate in the development of the kernel and the protocol, nothing has changed radically. Neither  added multi-devices, video and audio are not fixed, there are problems  with network detection of other clients, there is no delayed message  transfer. I hope all the same for the most active development. It just hurts to see how the great idea of a great messenger dies. I like it very much. Let's all together take up the development, testing, promotion and use. What do you say?

**Comment by mannol** [comment]
Yes-------- Original Message --------Subject: Re: [TokTok/c-toxcore] [discussion] Future of the project (#476)From: Alexey Suvorov To: TokTok/c-toxcore CC: mannol ,Mention Hey. Say, Tox is dead or not? Since Irungentoo ceased to participate in the development of the kernel and the protocol, nothing has changed radically. Neither  added multi-devices, video and audio are not fixed, there are problems  with network detection of other clients, there is no delayed message  transfer. I hope all the same for the most active development. It just hurts to see how the great idea of a great messenger dies. I like it very much. Let's all together take up the development, testing, promotion and use. What do you say?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/TokTok/c-toxcore","title":"TokTok/c-toxcore","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/TokTok/c-toxcore"}},"updates":{"snippets":[{"icon":"PERSON","message":"@alexeysvrv in #476: Hey. Say, Tox is dead or not? Since Irungentoo ceased to participate in the development of the kernel and the protocol, nothing has changed radically. Neither  added multi-devices, video and audio are not fixed, there are problems  with network detection of other clients, there is no delayed message  transfer. I hope all the same for the most active development. It just hurts to see how the great idea of a great messenger dies. I like it very much. Let's all together take up the development, testing, promotion and use. What do you say?"}],"action":{"name":"View Issue","url":"https://github.com/TokTok/c-toxcore/issues/476#issuecomment-307650204"}}}

**Comment by GrayHatter** [comment]
@mannol  is right, tox is dead!

Everyone should move on to something else and let the devs work in peace...

**Comment by nurupo** [comment]
>Let's all together take up the development, testing, promotion and use. What do you say?

I think you are missing the point of the issue we are having. That's what we are doing, we are, all together, the whopping one and a half of a person, taking up the development, testing, promotion and use, all this time. The issue is that there are too few of us, and everyone has limited time for Tox. There are only so much a few folks can do, and your complaining doesn't really help with increasing number of developers or the free time they can, and willing to, spend on working on Tox.

**Comment by Zer0-One** [comment]
> I think you are missing the point of the issue we are having. That's what we are doing, we are, all together, the whopping one and a half of a person, taking up the development, testing, promotion and use, all this time. The issue is that there are too few of us, and everyone has limited time for Tox. There are only so much a few folks can do, and your complaining doesn't really help with increasing number of developers or the free time they can, and are willing to, spend on working on Tox.

'nuff said. If I had a nickel for every "future of the project" post...
