### ISSUE TITLE
Periodic disconnect from DHT on fast corporate network

### ISSUE THREAD

**Issue by anthonybilinski** [TokTok/c-toxcore#580]
Follow up from https://github.com/qTox/qTox/issues/4559

I'm on a fast computer on a 1 Gbps up/down corporate network. There are some firewalls in place, but it seems like just DNS + specific outoging ports. With both qTox (about every 30 minutes) and uTox (about every 15 minutes) I see "Disconnected by DHT" followed by "Connected to DHT" a few seconds later.

The disconnects are not synchronous when I'm running both clients simultaneously, so I think it may be a toxcore problem instead of a network/filtering problem.

I'm able to wireshark (some in qTox ticket linked) or do other debugging to look in to this.

**Comment by anthonybilinski** [comment]
I added some logs to toxcore and ran for a while, here's what I collected:
[disconnect.txt](https://github.com/TokTok/c-toxcore/files/1278414/disconnect.txt)

each "..." represents one or more calls to tox_iterate.

So basically, it keeps sending out announces, then for 15s+ it just doesn't get an answer, so it starts reporting timeout and the clients think they are offline and re-bootstraps. Re-bootstrapping seems to always work quickly.

My guess would be some NAT issue, since it appears to be periodic and not in-sync for two clients running at once, but I guess some bad filtering is also possible.

**Comment by zugz** [comment]
* Tuesday, 2017-09-05 at 18:14 +0000 - Anthony Bilinski <notifications@github.com>:

>So basically, it keeps sending out announces, then for 15s+ it just 
>doesn't get an answer, so it starts reporting timeout and the clients 
>think they are offline and re-bootstraps. Re-bootstrapping seems to 
>always work quickly.

Interesting. Is UDP disabled/blocked? If so, I wonder if the problem 
could be that your connection to the TCP relays is being blocked for 
some reason. It looks like this could easily go undetected by TCP_Client 
for 15 seconds, so then the onion would timeout before new relays would 
be connected to.

If this is the problem, switching to the latest version of toxcore might 
actually "fix" it, because a side-effect of some recent changes was to 
increase the timeout for disconnection from the onion.

This wouldn't explain the difference in period between uTox and qTox, 
though...

**Comment by anthonybilinski** [comment]
I am using UDP, and as far as I know it's not blocked, unless the method of blocking is dropping responses for 15 seconds every 30 minutes :P

I was off version 1.2 before, as per qTox build instructions. I updated to (4ceaad50) and still see disconnects with the same frequency, but with different errors.

I'm now hitting the case at the bottom of onion_isconnected where (pnodes / 2) <= num is false, after not getting responses from announces for 15s+

log: 
[disconnect-tip.txt](https://github.com/TokTok/c-toxcore/files/1279391/disconnect-tip.txt)

**Comment by zugz** [comment]
OK. You could check the diversity of the entry nodes by adding the ip 
address and ip.family of the path->ip_port1 to your debug output on 
sending a request. I'd add the destination too.

**Comment by anthonybilinski** [comment]
I assume destination is ip3? I've logged the case assuming that
Output format is:
```
    ip_parse_addr(&path.ip_port1.ip, toPrint, sizeof(toPrint));
    printf("[%lu] sent announce request to [%u]%s:%u\n", unix_time(), path.ip_port1.ip.family,
    		toPrint, path.ip_port1.port);
    ip_parse_addr(&path.ip_port3.ip, toPrint, sizeof(toPrint));
    printf("[%lu] with destination [%u]%s:%u\n", unix_time(), path.ip_port3.ip.family,
    		toPrint, path.ip_port3.port);
```
I had couple of my contacts running locally on the same machine as this log was generated on, and replaced my LAN IP with "[localhost]", and I replaced my LAN friend's IP with "[LAN-friend]".

[dht-disconnect-with-ips.txt](https://github.com/TokTok/c-toxcore/files/1282980/dht-disconnect-with-ips.txt)

**Comment by zugz** [comment]
Thanks. That's enough to prove that my theory was wrong. However:

* Wednesday, 2017-09-06 at 23:29 +0000 - Anthony Bilinski <notifications@github.com>:

>I assume destination is ip3? I've logged the case assuming that 

No, ip3 is the third onion node in the path. Assuming you're doing this 
in send_onion_packet_tcp_udp, the destination IP_port is 'dest'.

But it doesn't make any sense for there to be a problem with the 
destinations - your corporate firewall can't do anything on that end.

I'm not sure what to advise for further debugging. I guess I'd try to 
see if the problem affects all udp traffic, rather than just tox. 

I'm expecting that this isn't actually a bug in tox.

**Comment by anthonybilinski** [comment]
I ran some little network tests between a VPS I have running a TCP and UDP echo server with no NAT, and my home machine (behind NAT) to the same server. From home, both TCP and UDP work fine on 33445 and higher ports, also on arbitrary sub-1024 ports. At work, neither TCP nor UDP work on 33445 or other high ports, nor sub-1024 - but TCP does work on my SSH , HTTP, HTTPS ports.

So it does look like my work firewall is probably messing things up, and for this test it affects both TCP and UDP, but only on some ports. I don't understand how I then have a working Tox connection to the DHT at all, when the family is usually IPv4 UDP on sent announces, and ports are either 33445 or a little higher, which also fail when I test with netcat..

**Comment by zugz** [comment]
I don't understand it either. There are a few bootstrap nodes running 
TCP relays on 443, but it seems from your logs that you aren't using 
those as entry nodes in the onion, and instead plenty of packets to high 
ports are getting through for a while.

**Comment by anthonybilinski** [comment]
Well, it seems confirmed that this isn't originating in Tox, and without understanding what's going on at a network level here it's unreasonable to expect some kind of workaround. Maybe if some sysadmin with weird corporate firewalls comes across this problem they can shed some light on it :P

**Comment by pizdjuk** [comment]
Had the same issue just yestearday talking with my friend.
