### ISSUE TITLE
Popularity of Tox

### ISSUE THREAD

**Issue by tox-user** [TokTok/c-toxcore#619]
When reading older issues or this wikipedia article https://en.wikipedia.org/wiki/Tox_%28protocol%29#Reception it seems that Tox used to be much more popular that it is now. Looks like it had more active contributors too. What happened? Can we do anything to change it? Why doesn't Tox participate in Google Summer of Code anymore?

**Comment by redmanmale** [comment]
Newspapers write news; when Tox was new it was cause to write about it. So that part's quite clear.
I don't know anything about the rest though.

**Comment by jin-eld** [comment]
I've been interested in Tox from the early days, I've also been contributing back then (I simply don't have time now). Tox started when Snowdens revelations were a big thing, everything related to NSA and global surveillance was picked up by news sites and channels, Tox was on that wave. After that nothing really happened, people kept using their smartphones, they kept selling out their private data just out of convenience. So that hype was gone at some point.

Project wise - Tox and Tox clients are still not included in major Linux distros, Tox is not part of standard distro repositories, I think this is a very important aspect that would help to gain more popularity. Are there any releases? Correct me if I'm wrong, but I think there are none... it's still marked as "in development". People usually don't like things that are "in development", people expect a stable release.

I still use Tox and given how terrible Skype has become (honestly, back then I could not imagine it could get worse, but it actually did!) I would really like to see a stable Tox release going into all major distros. I had a Tox call with my buddy today - the audio quality was way better than with the newest Skype client. Tox could present itself as option. It works!

It is my understanding that the main reason for not having a release marked as "stable" is the promise of being totally secure which is not yet fully met (or is it?), but maybe it's time to take a step aside from the goal to guarantee full security from the very beginning and for starters just become a good messenger for audio and video calls, which imho Tox is already fully capable of.

Just my 2 cents.

**Comment by redmanmale** [comment]
I couldn't say much about the rest Tox clients but I've been using uTox for more than four years now and it's quite stable from user's POV.

**Comment by tox-user** [comment]
Wow, I didn't know Skype could get any worse! I think it's why Discord got so popular? It is true that we don't hear that much about illegal spying as we did back then, but on the other hand we now have many more apps for secure messaging: Signal, Riot, Jitsi. I don't know for sure what qualifies as stable, but I would say that uTox and qTox are stable clients (I haven't used any others yet). Tox still misses a few important features like offline messaging, but I think it's ready to be included in distros. For Tox to be secure it would need a security audit, right? Then we need more people using it to be able to do that. Making Tox more available would definitely help with that goal! Other thing that attracts users are new features and we don't get too many of them. Also many people won't switch to Tox until their friends start using it.

**Comment by tox-user** [comment]
Also what is up with https://github.com/irungentoo/toxcore ? When you search for toxcore it's the first thing that pops up. Why doesn't @irungentoo change the readme to redirect people here? When someone goes there and looks at the commits they might think that Tox is abandoned.

**Comment by jin-eld** [comment]
I was not talking about "stable" in the usability sense of the word, but merely about how developers label the project - has there been a release announcement and a versioned toxcore library tarball? I don't see one... when I was more involved in the project it was still very much in a "being developed" state, even though it was already functioning for the users point of view.

Of course it's up to the developers to decide when a project is "ready" for the 1.0.0 release, I'm only saying - not having a "release" and not being in the distros does not help. Your friend will most likely not install any client that he or she will have to compile first and personally I am not a fan of third-party binary packages either. Being in a distro b default is a huge boost for a project and I'm talking from first hand experience here...

**Comment by tox-user** [comment]
@jin-eld I found this https://blog.tox.chat/2016/12/first-stable-release-of-toktok-toxcore/

**Comment by jin-eld** [comment]
OK, I guess I missed that... then.. why aren't Tox clients (or at least one) in all major distros?

**Comment by tox-user** [comment]
For qTox it's because there is noone to make packages :(
https://qtox.github.io/blog/2017/02/15/Maintainer-Wanted.html
https://github.com/qTox/qTox/issues/4816

Other clients are available in tox's own repo https://tox.chat/download.html#gnulinux but I don't know why they aren't in distros.

**Comment by jin-eld** [comment]
Tox's own repo is not the same as being in a distro...

I am not sure how this works either, my project simply ended up almost everywhere and I think for some distros we searched for maintainers on the dedicated distro mailing lists.

Another possibility is to prepare an rpm/deb yourself according to the distro guidelines and submit it, it may take a couple of cycles to get it right, but if it meets all the requirements in the end they usually accept it.

**Comment by tox-user** [comment]
Looks like someone tried to package Tox for Debian: 
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=739860
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=764071
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=770915
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=788040

**Comment by ethylmorphine** [comment]
The great thing about uTox is that you can static build it and distribute as “download the single binary file and run”. The same approach shares such projects as SunVox, for example. However, do apt/rpm things in the terminal is much more linux-way.

**Comment by zoff99** [comment]
@jin-eld TRIfA is in the playstore and on official f-droid
i call that "all major distros" at least for android

**Comment by jin-eld** [comment]
> i call that "all major distros" at least for android

I guess I would not know because I don't use android. Nor do I use iOS ;) Or any other devices that spy on you :>

It's good to hear that it is available there. Still, imho linux distros plus windows binaries (I think those are already available) is a must.

As for static binaries - I was indeed using qTox static builds, but I think there are none offered any more. And as correctly noted, this is not the "linux-way" and everything that is custom will not spread as fast as something that is just there by default and is included in the regular update cycle.

In the end it's up to us, users, to convince friends to try it out. The above points would simplify this task a lot.

**Comment by tox-user** [comment]
Antox is also in Android's store and on f-droid. Antidote is in iOS's app store. It's good. The only OS left without an easy way to install Tox is GNU/Linux (except a few distros).

Can someone answer what is going to happen with Tox as an organization? Will it start taking donations, will it participate in Google Summer of Code again? I think Tox could easily beat many more popular apps, but it needs a boost.

**Comment by fcore117** [comment]
tox-user: Biggest issue with Linux is there are still no single standard for so called "setup" but i see hope in Appimage/Flatpak to make downloading and running/installing apps easy in future. Currently uTox is only one for Linux that you just download and then run, qTox should use Appimage or Flatpak.

**Comment by zoff99** [comment]
Antox is not in the offical f-droid store

**Comment by jin-eld** [comment]
@fcore117: I disagree, each distro offers a graphical package manager for those who can't just type "dnf install qtox" (apt-get or whatever) in the console. There you could easily select qtox from a list and hit the install button. It can't really get easier than that... The problem right now is that qTox/uTox/etc are not in that list...

**Comment by dingosan** [comment]
I too have noted a slowing down of effort and find it unexplainable. The feature set on the mobile platforms is quite basic yet it still lacks in stability esp on Android. Laugh as you might but it is the computer you have in your pocket 99% of the time you need to communicate with someone. That is the case with most people...and hence if tox isn"t a solid messanger on that platform people will go elsewhere.....signal? Personally, I would love to see Tox go to the area of email. This is where security is seriously lacking and spam is rife.. Imagine for a start Markdown suppport on all clients. Imagine a separation of contacts and conversations in the sense that if I delete a conversation I should not have to scan your pub key to start another one with you. Then conversations should be grouped in any way you like say on a topic or subject line....so we could have a conversation on Tox and a separate (visually) conversation about the weather and a separate one about plans for tomorrow....with full support for attachments.....why? Because  it is far more constructive to focus conversations down to single subject so that it can stay on topics and then once a topic/project is done with delete or archive it to recover storage space etc. Imagine how many people would jump on it when they find out it has (tox) zero spam.. And it will always have so... unlimited attachments think videographers working on a film... high need for privacy and huge data transfer needs but usually mail servers have various pathetic attachment data limits, the need for mail servers and their other policies and logging... Imagine human rights reporters in hostile environs needing to send footage quickly and securely and SAFELY off. Imagine documenting police brutality...SNOWDEN etc Various other scenarios where email and pgp leave much to be desired. But mostly because we need to upgrade away from the monitored world of email for all our other projects be they schoolwork or business discussions that we dont want the isp's mail administrator reading etc. Let's make this TOX baby fly instead of just texting...which is also important.  What do you mean it has no outbound que, it should have been there from day one....how else does one compose a reply offline? It would go a long way to solving queuing issues? And ofcourse the more you and your contact use Tox then the likeliness of you being online at the same time increase dramatically. Perhaps this could be enhanced with push notifications but that should be optional at the client. There is just soooo much potential but lets just get the mobile clients to a solid start first. Then add Markdown across the board followed by outbound queuing and conversations grouping and full attachment support. This would see huge rise in usage. Actually if you look at the DHT usage graphs it is growing but yeah I think Signal has definetly taken a big chunk of users away from Tox and we  need a solid focus to regain ground....email is that ground. What do you all think?

**Comment by tox-user** [comment]
If there is an issue with a mobile client you should report it in their repository (https://tox.chat/clients.html). I'm not sure what you mean by full support for attachments, because you can already send files. But there is no offline messaging yet, which is one of the missing features. If Tox had that and multi device support it would probably be better than email. I don't think that would be enough to get rid of email though. Even if Tox gets very popular not everyone will be using it. Plus you still need an email account to register on any website, because that's how web works. You can group conversations by creating groupchats, but I personally don't see how it could be useful. Most people probably don't chat like that. Also that is most likely a client issue. Same with markdown. If you want those features you need to talk about them with client developers.

**Comment by peterhoeg** [comment]
FWIW, we're shipping both uTox and qTox in [NixOS](https://nixos.org).

**Comment by dingosan** [comment]
Nope it is an architecture issues imho, way too much traffic pinging peers or whatever. That actually is not just an issue on the mobile platforms some laptop users have limited 3/4G plans too. Hell a lot of laptop people tether to their mobiles when away from ther usual haunts...say on a trip and to have your data allowance blown away by your idle messanger is just poor form. This aspect I see as needing urgent rethink before full release as it could and would generate a lot of bad press amongst users. Why n the core? Because these algorithms, poles and timeouts need to be consistent to all clients for the whole ecosystem to be stable and efficient.

**Comment by ubone** [comment]
the tox name is unfortunate imo

when you hear TOX it just repels because the closest thing you think of is toxic
(which is something you wouldn't want)

it would be good to change tox with tok for the client's names because they are as far as
the end user will go anyway, for example: qTox > qTok and uTox > uTok

tok sounds nice and the next closest thing you think of when you hear it is talk which is what you're about :)

**Comment by r4de** [comment]
The client-devs here wait if the guys from TokTok will make toxcore web(browser) compatible ( issue #597 ).
No one want to install Addons, Plugins, Clients - it must work 'out of the box' - join an url and chat ;)

**Comment by naxuroqa** [comment]
@ubone any name suggestions for Venom as well? Due to recent (unrelated) movies of the same name, I would not be opposed to change the name to make it more appealing.

**Comment by sudden6** [comment]
@naxuroqa Matrix also is movie and a chat client, maybe the combination isn't too bad ;)

**Comment by naxuroqa** [comment]
@sudden6 well that's also true :)

**Comment by iphydf** [comment]
Closing this as unactionable at this time.
