### ISSUE TITLE
WIP: Video bug found!

### ISSUE THREAD

**Issue by zoff99** [TokTok/c-toxcore#620]
this bug causes all of these (i am pretty sure)

#235 
#618 

https://github.com/qTox/qTox/issues/2529
https://github.com/irungentoo/toxcore/issues/1479
https://github.com/irungentoo/toxcore/issues/1474
https://github.com/irungentoo/toxcore/issues/1479

https://github.com/irungentoo/toxcore/pull/1525

**Comment by zoff99** [comment]
solution:

https://github.com/zoff99/c-toxcore/compare/8c9cec470d5feb12de2123e48a4096364a113867...zoff99:10217ea1ace48bd8cc098f4a689701e7e5741d3b

**Comment by Diadlo** [comment]
@zoff99 Are you "pretty sure" or you test it?)
If you want, in the evening I can take part in the test

**Comment by zoff99** [comment]
@Diadlo i have tested it. but yes please contact me in the evening, that would be good

**Comment by nurupo** [comment]
You should keep the aligment checks and dummy variables, they are there because mannol did what should not be done -- sending those structs over the wire as they are, meaning that sizes of those structs must be the same for the dender and the receiver, for any CPU architecture, no matter the alignment. If the alignment is not the same on all machines, then the code is broken and you might get garbage for video and possibly memory overwriting vulnerabilities.

**Comment by nurupo** [comment]
Also, since those structs are sent over the wire, I don't think this change would be backwards-compatible with existing tox clients as it would change the size of those structs. This should work only between patched tox clients. So this is a protocol breaking change. We might want to change the packet ids for the video or something, so that older clients and patched clients couldn't do video with each other, because it's likely to result in garbage and memory issues for some CPU architectures.

**Comment by nurupo** [comment]
Other than that, it looks good. So, the issue was that 16-bit size was too small? @mannol you might want to look into this.

It seems like this is commit is made on top of your other commits, I see some `// Zeoff` comments that are nit counted in the diff, would be nicer if it was on top of c-toxcore master, in case there is more of diff that helped fixing the issue that we are not seeing.

**Comment by nurupo** [comment]
Btw, in your commits you write

>/*
>vpx_codec_err_t vpx_codec_decode 	( 	vpx_codec_ctx_t *  	ctx,
>		const uint8_t *  	data,
>		unsigned int  	data_sz,
>		void *  	user_priv,
>		long  	deadline 
>	)
>
>here you can cleary see it
>"data_sz" is 32bit unsigned
>*/

The size of `int`, unsigned or not, is platform-dependant. It might be 16-bits, or 32-bits, and I wouldn't be too surprised to see it being 64-bits. The C standard only specifies the minimum range for the primitive types, and `int` is said to be at least 16 bits. So 

>here you can cleary see it
>"data_sz" is 32bit unsigned

Is not incorrect for some platforms. A more correct statement would be that size of `data_sz` is at leat 16 bits, or that `data_sz` is exactly `sizeof(data_sz)`.

Since our code depends on it, it would be wise to add some compile-time assert checks for sizes, e.g. `static_assert(sizeof(data_sz) <= size(uint32_t))`, and all other variable size assumptions. (Note that there is no `static_assert` in C, at least C99, but it's an easy to write macro, you can google it).

**Comment by zoff99** [comment]
@nurupo i already wrote that

![image](https://user-images.githubusercontent.com/6833516/33210536-f8a7cfa6-d11a-11e7-8440-224ebd738e0e.png)

also a keyframe is easily 200kbytes in size, when you use 16bit for size it can never ever work.

**Comment by nurupo** [comment]
>also a keyframe is easily 200kbytes in size, when you use 16bit for size it can never ever work.

Right, I'm not arguing about that. I'm saying that `int`'s size is platform-dependent, so saying that it's 32-bit in size is incorrect for some platforms.

**Comment by nurupo** [comment]
@SkyzohKey why is this issue in Security project? It's not about security.

**Comment by SkyzohKey** [comment]
@nurupo Cannot this bug be exploited and compromise security (buffer overflow, use after free, etc)?
I'm not really a security expert thus asking

**Comment by zoff99** [comment]
@nurupo 
well vpx source code defines it like that. so ask the WEBM project what size they actually mean :-)


vpx_codec_err_t vpx_codec_decode ( vpx_codec_ctx_t * ctx,
const uint8_t * data,
***unsigned int data_sz,***
void * user_priv,
long deadline

**Comment by Diadlo** [comment]
Mostly issue really fixed. Still have some problems, but just small

![image](https://user-images.githubusercontent.com/6306608/33224660-f391f1f6-d17c-11e7-8f4a-2d4bf5fb7958.png)
![image](https://user-images.githubusercontent.com/6306608/33224662-f61b76fe-d17c-11e7-9b00-e6269c9ff47b.png)
![image](https://user-images.githubusercontent.com/6306608/33224664-f9087ace-d17c-11e7-9cf3-e8c5d0fd8214.png)

**Comment by mannol** [comment]
OK, after some analysis here are my findings:
- This was definitely an issue (spot on @zoff99!)
- Changing the RTPheader breaks the protocol (very undesirable)
- Might be fixed without breaking the protocol (a possibility)

It's been a long time since I last wrote code for toxav (about 2 years or something?), but, IIRC, vpx decoder shouldn't care how encoded chunks are packed as long as they are ordered correctly. That being said, changing [this](https://github.com/TokTok/c-toxcore/blob/master/toxav/toxav.c#L816-L825) loop in a way that **splits the payload into multiple RTP messages** might just be the solution we are looking for.

**Comment by zoff99** [comment]
@mannol you still do not understand the what the issue is.

**Comment by mannol** [comment]
@zoff99 I don't?

**Comment by zoff99** [comment]
@mannol 
if you video frame from the encoder has 65537 bytes and you take uint16_t from that you get the number 1. then you send "1" in the RTP Message as data length.
on the other end the decoder will give corrupt frame always. video will never show.
my emergency hotfit will at least fix this critical issue

**Comment by mannol** [comment]
@zoff99 That's what I'm saying: spit the video frame from the encoder (larger than 64K) into multiple RTP messages (smaller than 64K). The decoder should be OK handling these chunks independently as long as they are in order (which they most likely will be).

**Comment by zoff99** [comment]
wont work. also 0.2.0 will break things anyway. so lets do it there and also include VP9. which also works fine.
i just fear 0.2.0 will take forever to arrive with TokTok's commit policy

**Comment by mannol** [comment]
@zoff99 you tried it already?

**Comment by zoff99** [comment]
@mannol rather look at my emergency hotfix. to save at least what is there already

**Comment by zoff99** [comment]
@mannol ---> rather continue in tox msgner?

**Comment by mannol** [comment]
@zoff99 what?

**Comment by GrayHatter** [comment]
> We might want to change the packet ids for the video or something, 

No, I have a better solution for this. ToxAV will get a single packet number, and then it can wrap it's traffic with an additional ID if ToxAV needs to. Toxcore shouldn't be abartrating ToxAV inner workings.

> well vpx source code defines it like that. so ask the WEBM project what size they actually mean :-)

It dosen't matter what they mean/want. Toxcore is a security/crypto project, VPX isn't... We should do what we want to do. u32 seems to be that, no?

> my emergency hotfit will at least fix this critical issue

It's not an emergency hotfix, mostly because it's not hot, not really a fix for this issue, nor emergency. 

The real fix (from my view at least) would be to prepend all toxav packets with a "binary" blob with an arch independent layout, that ToxAV could then version, and pass into a handler that could then pass back a struct for the *current* version of ToxAV, making all future changes backwards compat. (Hopefully)

I'm also going to echo what @nurupo said. Open a pull to the toxcore repo with JUST these changes so I can review the changes, and maybe merge them into my toxcore fork.

**Comment by zoff99** [comment]
exactly my thinking, long term the need to be protocol versions. but not only for ToxAV, but for all.
there will be protocol breaking thing every now and then.
so nodes need to announce what protocol they are speaking.

**Comment by sudden6** [comment]
@mannol I think splitting this loop can cause additional problems:

* IIRC toxav packets are lossy, so there may be packets dropped, which probably will cause problems.
* packets may arrive out of order, will RTP handle this case?

**Comment by mannol** [comment]
@sudden6 
> IIRC toxav packets are lossy, so there may be packets dropped, which probably will cause problems.
RTP message is already split in chunks of ~1.5KB in size, regardless of it's actual length so increasing the RTP message size will mean that you send more of those chunks. RTP works in lossy environment, there are mechanisms for packet reordering and loss handling.
> packets may arrive out of order, will RTP handle this case?
They may but, the jitter buffer will likely order them correctly. Lossy packets are not as "lossy" as they seem to be so that is not a big problem.

**Comment by sudden6** [comment]
Ok, then that's very good.

**Comment by nurupo** [comment]
@SkyzohKey no, it's not exploitable. The bug is that if the video packet is greater than 65535 bytes in size, only `<packet-size> mod 65536` bytes of it will be sent, i.e. between 0 and 65535, dropping the rest of the frame. No uninitialized memory is sent and no way to exploit it, at least as far as I can see.
