### ISSUE TITLE
[Question] What are the features that needs to be worked on first?

### ISSUE THREAD

**Issue by SkyzohKey** [TokTok/c-toxcore#634]
Hey guys,

Since a long time now Tox didn't evolved that much and I was willing to ask what would be the principal feature you'd like to see work happens on first so lets poll that!

[![](https://api.gh-polls.com/poll/01C12DFEEY0YCQ5X6VJTJZQEKY/New%20Groupchats)](https://api.gh-polls.com/poll/01C12DFEEY0YCQ5X6VJTJZQEKY/New%20Groupchats/vote)
[![](https://api.gh-polls.com/poll/01C12DFEEY0YCQ5X6VJTJZQEKY/Improved%20documentation)](https://api.gh-polls.com/poll/01C12DFEEY0YCQ5X6VJTJZQEKY/Improved%20documentation/vote)
[![](https://api.gh-polls.com/poll/01C12DFEEY0YCQ5X6VJTJZQEKY/Multi%20devices%20)](https://api.gh-polls.com/poll/01C12DFEEY0YCQ5X6VJTJZQEKY/Multi%20devices%20/vote)
[![](https://api.gh-polls.com/poll/01C12DFEEY0YCQ5X6VJTJZQEKY/Decentralized%20Offline%20Messaging)](https://api.gh-polls.com/poll/01C12DFEEY0YCQ5X6VJTJZQEKY/Decentralized%20Offline%20Messaging/vote)
[![](https://api.gh-polls.com/poll/01C12DFEEY0YCQ5X6VJTJZQEKY/Decentralized%20Name%20Lookup)](https://api.gh-polls.com/poll/01C12DFEEY0YCQ5X6VJTJZQEKY/Decentralized%20Name%20Lookup/vote)
[![](https://api.gh-polls.com/poll/01C12DFEEY0YCQ5X6VJTJZQEKY/Independant%20Security%20Audit)](https://api.gh-polls.com/poll/01C12DFEEY0YCQ5X6VJTJZQEKY/Independant%20Security%20Audit/vote)
[![](https://api.gh-polls.com/poll/01C12DFEEY0YCQ5X6VJTJZQEKY/Better%20File%20Transfers%20support)](https://api.gh-polls.com/poll/01C12DFEEY0YCQ5X6VJTJZQEKY/Better%20File%20Transfers%20support/vote)

**Comment by ethylmorphine** [comment]
Why offline messaging is not an option?

**Comment by SkyzohKey** [comment]
@ethylmorphine Did you read the options? o.o

**Comment by zoff99** [comment]
@SkyzohKey can you put "actual message send timestamps" on the list

**Comment by SkyzohKey** [comment]
@zoff99 Unfortunally nope, gh-polls doesn't [yet](https://github.com/apex/gh-polls/issues/10) allow to update a poll :/

**Comment by ethylmorphine** [comment]
@SkyzohKey Oh, my bad.

**Comment by tox-user** [comment]
Please add friend sharing. Currently you can't copy contact's Tox ID and send it to a friend unless you save it somewhere outside of Tox.

**Comment by tox-user** [comment]
Not that this poll isn't useful, but I think it's very unlikely that those those features will get finished in any reasonable amount of time. First the project needs to get more developers, build a bigger community. That should be the focus now. Then start working on those things. Otherwise Tox has very little chance of succeeding. The features you listed were demanded years ago and none of them are even close to being finished.

**Comment by SkyzohKey** [comment]
This poll is meant to prove that community don't care about stuff being done on the repo ATM and wants the features with the most votes. Average user don't care about tests or coverage. They want features, and I'm wanting to demonstrate that devs should put efforts on satisfying peoples that use the software instead of writing tests. New GC is the most wanted feature but we all work on different features instead. Why not to put effort on 1 project at a time, dedicating 90% of the devs to the task while the 10% remaining still continues working on spec/tests/coverage?

**Comment by tox-user** [comment]
I agree, but I don't think it's enough. It would be a much better way to spend the limited resources the project has, but even then how long it will take to develop those features? Months? Years? I'm afraid that developers will start leaving the project with time and people will start losing interest in Tox. Other projects get donations and hire devs full time. I think Tox needs to do the same. Maybe try to get help from Mozilla and other organizations that give money to free software projects? I'm glad that Tox exists, but the few people that still work on the toxcore are not enough. We need Tox to be big, so that we could all communicate through the internet securely.

**Comment by Diadlo** [comment]
@SkyzohKey Are you joking? Do you think the tests are interesting to any user? But the important question you did not add it poll is "support for old functions in working order" (equal to "writing tests")

**Comment by SkyzohKey** [comment]
@Diadlo To quote myself:

> Average user **don't care** about tests or coverage.

I'm not the average user and know that tests/coverage **is** important. But that's not what the average Joe think. Average Joe wants funny GIFs of cat, stickers, groupchats, etc.

**Comment by sudden6** [comment]
Although the average user may not care about non existing tests normally, they will suddenly care if something breaks because there were no tests or the code base became a huge mess ;)

IMO when doing a work estimate there should always be some time(10-30%) dedicated to "chore" tasks like code cleanup, tests and documentation. You can't really ask users to estimate how much time is needed for that, because how should they know if even we don't really know?

**Comment by zoff99** [comment]
@sudden6 yeah, so more documentation in this case

**Comment by tox-user** [comment]
Users might not care about those things, but they are necessary. The problem is that there aren't enough people working on toxcore, so they can't implement features. We need those features to make Tox more convenient and easier to use. Without them Tox will never really be a serious alternative to other apps (for most people). The solution is not to stop making tests, but to bring more developers to toxcore.

**Comment by SlugFiller** [comment]
I'm actually torn between GC and multi-device. I would actually say the latter could bring more people in. But discussion of the latter has often put the prior as a dependency.

Also, I don't think anyone is under the illusion that refactoring and test coverage matters to end users. But when pressed on the matter, devs here represented them as being a dependency for actual features. Don't know how valid such a statement is, but that is the attitude I've seen here.

I would like to "close the loop" on this dependencies issue by pointing out that it's more likely that Tox could attract more devs if it has full working functionality, just with some bugs. Some of the things missing feel like core features, and are probably enough for some devs to skip this project, and look for a different program instead.

**Comment by dingosan** [comment]
Yup offline, markdown, conversations grouping, file transfers in that order for me

**Comment by dingosan** [comment]
Actually, thinking about it more, I would put multi device support right after offline  so...... offline, multi device, markdown, conversations grouping, file transfers, others

**Comment by zoff99** [comment]
the votes are manipulated. so this has no value at all

**Comment by SkyzohKey** [comment]
@zoff99 How are the votes manipulated? I'm just ordering the list (more to less) when I can for better readability.

**Comment by sudden6** [comment]
@zoff99 If you don't add some proof or at least reasons for your statement it sounds very made up.

**Comment by Diadlo** [comment]
@SkyzohKey Just test it. 3/4 votes for "Better file transfer support" is mine. Made with click in different browsers with one account

**Comment by zoff99** [comment]
@sudden6 i voted 40 times, is 1 reason

**Comment by SlugFiller** [comment]
Seems like this poll did more to emphasize the feature GitHub need to work on the most, rather than Tox.

**Comment by sudden6** [comment]
@SkyzohKey I think we should do the vote with 👍 on a comment for each option

**Comment by SkyzohKey** [comment]
Oh. Cannot you guy focus on the Tox features you'd like instead of pointing out that gh-polls needs to authenticate people with GH handle instead of IP address?

**Comment by Diadlo** [comment]
@SkyzohKey They even not check IP. I don't use any proxy

**Comment by redmanmale** [comment]
> A single vote per IP is allowed for a given poll, which are stored in DynamoDB.

From their About page.

@Diadlo Maybe your ISP provides you a dynamic IP.

**Comment by Diadlo** [comment]
@redmanmale You can test it yourself: copy vote link, open new incognito tab, paste and go, close tab, repeat

**Comment by sudden6** [comment]
If anyone is interested, I started a new poll here: #646 

Shouldn't be possible to trick that one as easily :)

**Comment by zoff99** [comment]
@sudden6 *POLL: Better File Transfer Support* --> what does this mean?
does it include persistent filetransfer even after offline or restart? (meaning saving FT structs in toxsave file)

**Comment by SlugFiller** [comment]
@zoff99 Storage decisions would seem more like a client/standards issue, than a core issue. I'd say it's more about allowing resuming a file transfer (i.e. allowing the receiver to request a byte range instead of the whole file), and maybe other torrent-like features for reliable partial transfers (e.g. hashtree requests). With protocol support for those, the rest will be up to the individual clients.

**Comment by sudden6** [comment]
@SlugFiller please edit the message in the other thread to follow the format or I'll have to delete it.

**Comment by zoff99** [comment]
@sudden6 resuming a filetransfer only makes sense if it's in toxcore (otherwise like now, some clients do some clients dont. its a mess).
but this in turn means saving pending FTs structs to the toxsave file.
but it should not be a big issue, since now if you have 10.000 friends the toxsave file will already be big.
also there is a memory issue already, if a friends sends you UINT32_MAX files, it will fill up your RAM pretty good

**Comment by SlugFiller** [comment]
@zoff99 Resuming can also mean pausing and resuming without restarting the client. Or pausing and resuming due to connection loss. It doesn't strictly have to involve persistence across restart. Again, beyond the ability to request specific byte ranges from an offered file, there's no reason why the specific feature set shouldn't be up to individual clients. A good example of this is chat history persistence, which has different formats for different clients. This would only become a problem for end users if they want to migrate clients in the middle of a file transfer, and still resume it. That's a bit of a stretch.

**Comment by zoff99** [comment]
@SlugFiller "Or pausing and resuming due to connection loss" --> thats is the same as restarting, since then your client will go offline.
it's bad to implement a standard feature in x number of clients, causing x number of different bugs.
and x maintainers need to keep that feature working

**Comment by SlugFiller** [comment]
@SkyzohKey So long as you're drafting that, I should probably request saving message signatures in the log as well. That could potentially be used to make things said on chat legally binding, without needing a specialized client to record the signatures. Although, this partially depends on the signature algorithm (as I've seen it mentioned elsewhere that the receiver can forge signatures using their private key and the sender's public key)
