### ISSUE TITLE
Bot Commands

### ISSUE THREAD

**Issue by amochkin** [TokTok/c-toxcore#842]
Hi, we are making IoT projects on Tox.
For this projects it would be awesome for Tox to support tags of bot commands.
For example, an IoT device would use a toxcore client (as we do now). And this client would have some means of advertising to all its contacts (peers) that it is a bot, and it support some specific commands.
Right now, as soon as IoT device and a user get connected over Tox, the IoT device sends a small greeting with further instructions. But it is much better to do it as in-band protocol.
Do you have any plans for cooperating with developers like us? Is there any possibility to submit a feature request?

**Comment by zoff99** [comment]
your clients can exchange any kind of data you need with this API:

tox_friend_send_lossless_packet()
tox_friend_lossless_packet_cb()

https://github.com/TokTok/c-toxcore/blob/master/toxcore/tox.h

**Comment by nurupo** [comment]
@zoff99 you misunderstood what @amochkin was asking about.

Modern IM platforms, such as Discord and others, have a "bot protocol", i.e. a client can declare that it's a bot, in contrast to a human user, and it can provide extra information on which commands it supports and such. @amochkin is asking that we add support of this in the Tox protocol and the toxcore library, so that all Tox clients and bots would support it. This would allow Tox clients to visually distinguish bot users from human users in the UI, as well as to provide additional information about the bot without bots having to resort to using the annoying "greeting messages" like the one @amochkin mentioned.

**Comment by sudden6** [comment]
I think that's the perfect use case for https://github.com/TokTok/c-toxcore/issues/513 and https://github.com/TokTok/c-toxcore/issues/777

Although, I think both of those are not very extensible.

**Comment by iphydf** [comment]
Clients can do this with custom packets.
