### ISSUE TITLE
Empty names in group chats

### ISSUE THREAD

**Issue by tox-user** [TokTok/c-toxcore#865]
In toxcore 0.2.1 names in group chats are often empty. In versions below 0.2.0 the name appears as "Tox User", which is the default name. Reconnecting to a group chat usually fixes the problem, but this happens very often when someone joins the chat and sometimes it even happens to our own name and we see ourselves as an empty string! It's an old and very annoying bug. Maybe there is something wrong with the way user names are received?

**Comment by nogaems** [comment]
I've been experiencing the same bug and re-run of the whole client (weechat with the [plugin](https://github.com/gordon-quad/tox-weechat) wasn't making any changes. I was trying multiple times and the same bug was reproducing. But after rebuilding toxcore lib from the upstream (2 commits ahead after the last rebuilding, that don't change any code affecting toxcore behavior) this bug just has appearently dissapeared. I'd like to know is that because of rebuilding or just some toxcore internal state that has changed for some reason and the whole thing is just a coincidence?

**Comment by iphydf** [comment]
https://github.com/irungentoo/toxcore/blob/master/toxcore/group.c#L768

We used to have "Tox User" as a default name. This is not internationalised and should be the client's responsibility, so we removed it.
