### ISSUE TITLE
Monolithic libtoxcore.so when built with cmake, 3 shared libs when built with autotools

### ISSUE THREAD

**Issue by gordon-quad** [TokTok/c-toxcore#869]
When I build toxcore using cmake it produces single monolithic `libtoxcore.so` which contains all symbols from libtoxav and libtoxencryptsave.

When I build toxcore using autotools it produces three shared libraries: `libtoxcore.so`, `libtoxav.so` and `libtoxencryptsave.so`.

I wonder if such behavior is expected and if not what is preferred method of building toxcore and is the other one going to be deprecated and removed later?

**Comment by SkyzohKey** [comment]
From the begining toxcore was effectively split into 3 libs. Then the cmake process has been reworked to produce only one lib as we've all seen how a pita it was to ship them separately. IIRC only CMake was reworked and thus autotools still produce the 3 toxcore libs. Which is in fact a cool thing so that people whose like the older way can still have 3 libs. And people that were pissed of by these 3 libs get it in only one. Everyone is happy c:

**Comment by gordon-quad** [comment]
It's just the problem that Gentoo tox-9999.ebuild still uses autotools approach and I was a bit confused by that.

**Comment by gordon-quad** [comment]
Maybe you have any even slight idea who maintains Gentoo ebuilds for tox?

**Comment by iphydf** [comment]
Our autotools build is deprecated and only used for vanilla-nacl builds.
