### ISSUE TITLE
Maybe need to set the stacksize for musl-libc

### ISSUE THREAD

**Issue by xhebox** [TokTok/c-toxcore#886]
Follow https://github.com/qTox/qTox/issues/5127.

I previously patched golang to let my tox bot work months ago, and now it's qtox. They all crashed due to the small stack size limit of musl-libc(80K).

Since there're already two applications having crashed, i think we should have a discussion: should the caller of the `setstacksize()` be applications, or the toxcore library?

I prefer patching library, since i just have 28 friends, plus the nodes info and so, it's so small a scale, but it crashed. It may be very easy to touch the stack size limit of musl, and patching library will make things much more convenient.

As for the size, 512K should be big enough, as i said in https://github.com/qTox/qTox/issues/5127. But i think we need to think more about it, estimating the stack size generally cost by the library. Anybody have idea on how to do this?

UPDATE: https://github.com/qTox/qTox/issues/5127#issuecomment-387507909. sudden6 pointed out that this maybe a bug or an oversight in toxcore or qtox, because toxcore should not take so much stack in his opinion.

**Comment by joao-o** [comment]
1 year later this is still here, I'm happy to inform that a reason for the crash has been found: there is indeed at least one oversight on the tox library on the function dht_save
on the file toxcore/DHT.c the variable clients is "allocated" on the stack, clients is an array that occupies 128k of memory, since this is the maximum stack size on recent musl, it was bumped up recently from 80k you get a stack overflow and the corresponding segfault. I shall fix this and report later if i find more oversights

Best
João

**Comment by xhebox** [comment]
wow, glad to hear that... i thought this thread was abandoned or somewhat. i will have a look into it sometimes later. :D

**Comment by nurupo** [comment]
Should be fixed in https://github.com/TokTok/c-toxcore/commit/00f2f41dbbc660d7554b4df8e8397272cc92e22f which should make it into the next release.

**Comment by xhebox** [comment]
OK, close. I will report if there is any more problem.

**Comment by joao-o** [comment]
After applying a patch like that i was able to get qtox working when I last tested it.
