### ISSUE TITLE
Feature request: Contacts exchange.

### ISSUE THREAD

**Issue by fling-** [TokTok/c-toxcore#890]
Allow sending/receiving contacts to/from your buddies.
Receiver should be able to accept or decline the exchange.
And the friend being sent should be able to distinguish this action from the regular friend request.

**Comment by DontShootMe** [comment]
Adding in the loop the contact to be exchanged !

A shares the contact B to a friend C

first the contact B must agree to be shared, after this agreement, the contact C is informed and can accept or decline

I think we could have a better control of our information with this system, knowing who have my contact sheet

**Comment by sonOfRa** [comment]
While I agree with the idea that we should be able to easily share contacts via Tox, I think what the suggesting of having both parties having to consent is currently not really feasible in tox.

Since you have already added them as a friend, you have their public key (and likely also their nospam), and you can just pass that on by copying and pasting it. By putting this extra restriction into the system we make it seem like the contacts are secret, but in reality they aren't. I don't like having that kind of security by obscurity in Tox.

**Comment by iphydf** [comment]
They might have changed the nospam. Yes, you can share the nospam you used to add that friend, but it's a poor UX if that then ends up not working. I don't consider this a security feature, but adding a way to ask the friend for their nospam makes sense for contact sharing, and this can be combined with a consent dialog.

**Comment by tox-user** [comment]
>They might have changed the nospam

Just like a phone number, someone's Tox ID might have changed. Maybe they changed their nospam or got a new profile. Still, it should be possible to share Tox ID of a friend, even if their ID might be unused by them. If you ask someone for a phone number to some friend, it might be outdated too. So this argument that we shouldn't allow users exchange Tox IDs of their friends makes no sense. Someone might have changed their ID, so what? This can happen with email addresses, phone numbers and everything else. We would have to stop exchanging any contact information, because it might change.

It would definitely be nice if you could send single contacts to someone like that, but mostly people should be able to right click on their friend, get friend's Tox ID and send it to someone in chat.

**Comment by dvor** [comment]
You cannot change your phone number or email address by pressing just one button, without loosing all our contacts. With nospam you can do that pretty easily.

**Comment by tox-user** [comment]
Maybe then your friends should get notified of your every change of nospam? Then they will always know your full Tox ID and will be able to share it with anyone. Then your Tox ID will become a little less private (your friends can always give it to anyone), but is it really a big issue?

**Comment by iphydf** [comment]
This can be implemented in clients.
