### ISSUE TITLE
c-toxcore and LGPL (question)

### ISSUE THREAD

**Issue by hkarel** [TokTok/c-toxcore#903]
I have a question: Can I use the implementation of the c-toxcore as a dynamic library in a commercial application with a closed source code? Is it possible to use the LGPL license?

**Comment by hkarel** [comment]
Well, then I would like to ask the developers of the c-toxcore to consider using a dual license GPLv3/LGPLv3.
I believe that the use of tox-networking in commercial applications can serve to popularize and spread of the tox-network. It is also possible that commercial developers will bring new proposals, find and fix errors. 
I do not in any way want to limit the free nature of the tox-network, but at the firm, where I work there are some practices that I can not make open due to trade secrets.

**Comment by endoffile78** [comment]
I think it would be a good idea for toxcore to be dual licensed under the GPL and LGPL but before we do that we need to get at least the major contributors to agree if not all of them.

**Comment by tox-user** [comment]
https://www.gnu.org/licenses/why-not-lgpl.html

**Comment by endoffile78** [comment]
The GPL is preventing toxcore from being used in more software. There are alternatives to toxcore that are not licensed under the GPL. If toxcore is licensed under the GPL and LGPL toxcore will still remain free and open source software while having the benefit of increased usage. Plus if a company decided to use toxcore in their product and they make changes they have to be released so other foss projects that use toxcore can benefit.

**Comment by tox-user** [comment]
Let's see if I understand this correctly:
1. Since toxcore is licensed under GPL3, people can't create closed source Tox clients unless they write their own library
2. You want to allow people to create closed source Tox clients based on toxcore
Let me know if misunderstood, because I thought the goal of Tox was to create a secure messenger?

Please do not support closed source or proprietary software. Making free software is already hard. Those companies already have an advantage over us and we can hardly compete with them. Free software projects can not afford millions on marketing like them. Please do not make it easier for them to create proprietary software that uses our work. This is exactly why copyleft licenses like GPL3 exist.

I want Tox to be popular too, but there are better ways to achieve that goal. We can do it by making a useful, secure and easy to use program with a strong community and not allowing people use our work to create potentially malicious closed source clients.

**Comment by tox-user** [comment]
Remember that it is possible (but hard) to make a commercial program that is free or open source. Commercial programs based on toxcore could still exist.

**Comment by sudden6** [comment]
@tox-user Wow, the page you linked reads like a motivational speak for going into war...

BTT:

I see some advantages and disadvantages about making c-toxcore LGPL:

Advantages

- Tox could gain popularity
- overall license situation is easier with LGPL IMO, for some companies GPL is an immediate road block (maybe because they don't know better)
- changes/bugfixes to c-toxcore must still be open sourced

Disadvantages:
- the major devs must agree on this change (unlikely)
- companies profit from work done by people for free
- Tox clients would also be open source and could be audited by everyone

I would not agree with changing the license. Mainly because I don't like it when people do something for free, because they have fun and want to make the world a better place, and then a company makes profit from that free labour without giving back to the original people. The GPL gives us a chance to prevent that. Mostly because the hard and tedious work (library) gets tightly coupled to the thing that makes profit (client).

I would however have no problem if a company decides to hire someone (hopefully me :P) just to re-implement the Tox protocol with the LGPL or a dual license. Because then my main problem point would not apply, the people who do the work also get benefits.

**Comment by tox-user** [comment]
>Wow, the page you linked reads like a motivational speak for going into war

It's a competition. Companies who make profit off their proprietary software don't want to lose it and sometimes do what they can to keep people from using alternatives, especially those that are free software and cost nothing. There have been cases where companies tried to hurt open source projects. Microsoft is one of the biggest examples (it's why some users are leaving GitHub). So yes, it is a war. I try to not contribute to projects that don't use a copyleft license. There are exceptions where the license needs to be more permissive, but Tox isn't one of them. Unrelated: today I found this interesting article about how Microsoft tried to push everyone into using their insecure Internet Explorer browser http://toastytech.com/evil/ieisevilstory.html.

**Comment by hkarel** [comment]
Well, the position is clear. Maybe it's for the best. If we (our firm) decide to use the tox-network, then really the best variant for us will be write the implementation ourselves. So we won't depend on someone else's decisions. Moreover, we do not need a full functional of the network, but only a part. So we have chances to cope with this work.

**Comment by iphydf** [comment]
The position is clear but irrelevant. We could not relicense toxcore if we wanted to, because we don't have the right to do that, and we'd need to ask permission from every contributor. Any one contributor can disagree with their work being licensed under LGPL, which means removing their contribution. All of this is likely impossible, and at the very least extremely time-consuming. I'd rather we focus the time we have on feature implementations and code health improvements than on administrative work that some company may benefit from. Feel free to take on the work of tracking down all the contributors and reverting their work if they don't agree, but I would suggest to any project member not to spend time on this.

I believe the question is answered, so closing this issue.

**Comment by hkarel** [comment]
Yes, thank you for the exhaustive answer.
